# NumPy, Pandas Series & DataFrame - 50 Practice Questions

## Comprehensive Data Science Practice

This notebook contains 50 carefully crafted questions and detailed solutions covering:
- **NumPy**: Arrays, operations, mathematical functions, broadcasting
- **Pandas Series**: Creation, indexing, operations, methods
- **Pandas DataFrame**: Creation, manipulation, analysis, advanced operations

Each question includes detailed explanations and multiple solution approaches where applicable.

In [35]:
# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Set display options for better output
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)
np.set_printoptions(precision=3, suppress=True)

print("Libraries imported successfully!")
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

# Set random seed for reproducible results
np.random.seed(42)
print("\nReady to explore NumPy, Series, and DataFrame questions!")

Libraries imported successfully!
NumPy version: 2.3.2
Pandas version: 2.3.2

Ready to explore NumPy, Series, and DataFrame questions!


# Part 1: NumPy Questions (1-17)

## NumPy Array Creation, Manipulation, and Operations

NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on these arrays.

In [36]:
# NUMPY QUESTIONS 1-4: Array Creation and Properties

print("="*70)
print("NUMPY QUESTIONS 1-4: Array Creation and Properties")
print("="*70)

# Question 1: Create different types of NumPy arrays
print("\n1. Create different types of NumPy arrays")

# 1D array from list
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D array: {arr_1d}")

# 2D array from nested list
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array:\n{arr_2d}")

# Array with specific data type
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(f"Float array: {arr_float}, dtype: {arr_float.dtype}")

# Array filled with zeros, ones, and specific values
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((2, 3))
full_arr = np.full((2, 3), 7)
print(f"Zeros array:\n{zeros_arr}")
print(f"Ones array:\n{ones_arr}")
print(f"Array filled with 7:\n{full_arr}")

# Question 2: Create arrays using NumPy functions
print("\n2. Create arrays using NumPy functions")

# Range arrays
arange_arr = np.arange(0, 10, 2)
print(f"arange(0, 10, 2): {arange_arr}")

# Linearly spaced arrays
linspace_arr = np.linspace(0, 1, 5)
print(f"linspace(0, 1, 5): {linspace_arr}")

# Identity matrix
identity = np.eye(3)
print(f"Identity matrix:\n{identity}")

# Random arrays
random_arr = np.random.random((2, 3))
print(f"Random array:\n{random_arr}")

# Random integers
random_int = np.random.randint(1, 10, size=(2, 3))
print(f"Random integers:\n{random_int}")

# Question 3: Array attributes and properties
print("\n3. Array attributes and properties")

sample_array = np.random.randint(1, 20, size=(3, 4, 2))
print(f"Sample array shape: {sample_array.shape}")
print(f"Number of dimensions: {sample_array.ndim}")
print(f"Total number of elements: {sample_array.size}")
print(f"Data type: {sample_array.dtype}")
print(f"Item size (bytes): {sample_array.itemsize}")
print(f"Total memory (bytes): {sample_array.nbytes}")

# Question 4: Array indexing and slicing
print("\n4. Array indexing and slicing")

# 1D array indexing
arr_1d = np.array([10, 20, 30, 40, 50])
print(f"1D array: {arr_1d}")
print(f"First element: {arr_1d[0]}")
print(f"Last element: {arr_1d[-1]}")
print(f"Slice [1:4]: {arr_1d[1:4]}")

# 2D array indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D array:\n{arr_2d}")
print(f"Element at [1,2]: {arr_2d[1, 2]}")
print(f"First row: {arr_2d[0, :]}")
print(f"Second column: {arr_2d[:, 1]}")
print(f"Subarray [0:2, 1:3]:\n{arr_2d[0:2, 1:3]}")

print(f"\nCompleted NumPy Questions 1-4!")
print("="*70)

NUMPY QUESTIONS 1-4: Array Creation and Properties

1. Create different types of NumPy arrays
1D array: [1 2 3 4 5]
2D array:
[[1 2 3]
 [4 5 6]]
Float array: [1. 2. 3.], dtype: float32
Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]
Array filled with 7:
[[7 7 7]
 [7 7 7]]

2. Create arrays using NumPy functions
arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array:
[[0.375 0.951 0.732]
 [0.599 0.156 0.156]]
Random integers:
[[8 5 4]
 [8 8 3]]

3. Array attributes and properties
Sample array shape: (3, 4, 2)
Number of dimensions: 3
Total number of elements: 24
Data type: int64
Item size (bytes): 8
Total memory (bytes): 192

4. Array indexing and slicing
1D array: [10 20 30 40 50]
First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at [1,2]: 6
First row: [1 2 3]
Second column: [2 5 8]
Subarray [0:2, 1:3]:
[[2 3]
 [5 6]]



In [37]:
# NUMPY QUESTIONS 5-8: Array Operations and Mathematical Functions

print("="*70)
print("NUMPY QUESTIONS 5-8: Array Operations and Mathematical Functions")
print("="*70)

# Question 5: Array reshaping and flattening
print("\n5. Array reshaping and flattening")

original = np.arange(12)
print(f"Original array: {original}")

# Reshape to 2D
reshaped_2d = original.reshape(3, 4)
print(f"Reshaped to (3,4):\n{reshaped_2d}")

# Reshape to 3D
reshaped_3d = original.reshape(2, 2, 3)
print(f"Reshaped to (2,2,3):\n{reshaped_3d}")

# Flatten array
flattened = reshaped_2d.flatten()
print(f"Flattened: {flattened}")

# Ravel (returns view if possible)
raveled = reshaped_2d.ravel()
print(f"Raveled: {raveled}")

# Question 6: Mathematical operations on arrays
print("\n6. Mathematical operations on arrays")

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")

# Element-wise operations
print(f"Addition: {arr1 + arr2}")
print(f"Subtraction: {arr1 - arr2}")
print(f"Multiplication: {arr1 * arr2}")
print(f"Division: {arr1 / arr2}")
print(f"Power: {arr1 ** 2}")

# Mathematical functions
print(f"Square root: {np.sqrt(arr1)}")
print(f"Exponential: {np.exp(arr1)}")
print(f"Logarithm: {np.log(arr1)}")
print(f"Sine: {np.sin(arr1)}")

# Question 7: Array aggregation functions
print("\n7. Array aggregation functions")

data = np.random.randint(1, 20, size=(3, 4))
print(f"Data array:\n{data}")

# Basic statistics
print(f"Sum: {np.sum(data)}")
print(f"Mean: {np.mean(data):.2f}")
print(f"Standard deviation: {np.std(data):.2f}")
print(f"Minimum: {np.min(data)}")
print(f"Maximum: {np.max(data)}")

# Axis-specific operations
print(f"Sum along axis 0 (columns): {np.sum(data, axis=0)}")  
print(f"Sum along axis 1 (rows): {np.sum(data, axis=1)}")
print(f"Mean along axis 0: {np.mean(data, axis=0)}")

# Question 8: Boolean indexing and filtering
print("\n8. Boolean indexing and filtering")

arr = np.array([1, 5, 3, 8, 2, 9, 4, 7, 6])
print(f"Original array: {arr}")

# Boolean mask
mask = arr > 5
print(f"Mask (arr > 5): {mask}")
print(f"Elements > 5: {arr[mask]}")

# Multiple conditions
condition = (arr > 3) & (arr < 8)
print(f"Elements between 3 and 8: {arr[condition]}")

# Replace values using boolean indexing
arr_copy = arr.copy()
arr_copy[arr_copy > 5] = 100
print(f"Replace values > 5 with 100: {arr_copy}")

# Using np.where
result = np.where(arr > 5, arr, 0)
print(f"Keep values > 5, others become 0: {result}")

print(f"\nCompleted NumPy Questions 5-8!")
print("="*70)

NUMPY QUESTIONS 5-8: Array Operations and Mathematical Functions

5. Array reshaping and flattening
Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to (3,4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to (2,2,3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]

6. Mathematical operations on arrays
Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2   0.333 0.429 0.5  ]
Power: [ 1  4  9 16]
Square root: [1.    1.414 1.732 2.   ]
Exponential: [ 2.718  7.389 20.086 54.598]
Logarithm: [0.    0.693 1.099 1.386]
Sine: [ 0.841  0.909  0.141 -0.757]

7. Array aggregation functions
Data array:
[[ 9  2 15  7]
 [12  8 15  3]
 [14 17  4 18]]
Sum: 124
Mean: 10.33
Standard deviation: 5.36
Minimum: 2
Maximum: 18
Sum along axis 0 (columns): [35 27 34 28]
Sum along axis 1 (rows): [33 38 53]
Me

In [38]:
# NUMPY QUESTIONS 9-12: Advanced Array Operations

print("="*70)
print("NUMPY QUESTIONS 9-12: Advanced Array Operations")
print("="*70)

# Question 9: Array concatenation and stacking
print("\n9. Array concatenation and stacking")

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(f"Array 1:\n{arr1}")
print(f"Array 2:\n{arr2}")

# Concatenation along different axes
concat_axis0 = np.concatenate([arr1, arr2], axis=0)
concat_axis1 = np.concatenate([arr1, arr2], axis=1)
print(f"Concatenate along axis 0:\n{concat_axis0}")
print(f"Concatenate along axis 1:\n{concat_axis1}")

# Stacking
vstack_result = np.vstack([arr1, arr2])
hstack_result = np.hstack([arr1, arr2])
print(f"Vertical stack:\n{vstack_result}")
print(f"Horizontal stack:\n{hstack_result}")

# Question 10: Array splitting
print("\n10. Array splitting")

large_array = np.arange(12).reshape(3, 4)
print(f"Large array:\n{large_array}")

# Split along axis 0 (rows)
split_rows = np.split(large_array, 3, axis=0)
print(f"Split into 3 parts along rows:")
for i, part in enumerate(split_rows):
    print(f"  Part {i+1}:\n{part}")

# Split along axis 1 (columns)
split_cols = np.split(large_array, 2, axis=1)
print(f"Split into 2 parts along columns:")
for i, part in enumerate(split_cols):
    print(f"  Part {i+1}:\n{part}")

# Question 11: Broadcasting examples
print("\n11. Broadcasting examples")

# Scalar with array
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
print(f"Array:\n{arr}")
print(f"Array + scalar ({scalar}):\n{arr + scalar}")

# 1D array with 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
print(f"2D array:\n{arr_2d}")
print(f"1D array: {arr_1d}")
print(f"2D + 1D (broadcasting):\n{arr_2d + arr_1d}")

# Column vector with row vector
col_vector = np.array([[1], [2], [3]])
row_vector = np.array([10, 20])
print(f"Column vector:\n{col_vector}")
print(f"Row vector: {row_vector}")
print(f"Broadcasting result:\n{col_vector + row_vector}")

# Question 12: Linear algebra operations
print("\n12. Linear algebra operations")

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")

# Dot product
dot_product = np.dot(A, B)
print(f"A · B (dot product):\n{dot_product}")

# Matrix multiplication using @
matmul_result = A @ B
print(f"A @ B (matrix multiplication):\n{matmul_result}")

# Transpose
print(f"Transpose of A:\n{A.T}")

# Determinant and inverse
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(f"Determinant of A: {det_A}")
print(f"Inverse of A:\n{inv_A}")

print(f"\nCompleted NumPy Questions 9-12!")
print("="*70)

NUMPY QUESTIONS 9-12: Advanced Array Operations

9. Array concatenation and stacking
Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Concatenate along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1:
[[1 2 5 6]
 [3 4 7 8]]
Vertical stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack:
[[1 2 5 6]
 [3 4 7 8]]

10. Array splitting
Large array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Split into 3 parts along rows:
  Part 1:
[[0 1 2 3]]
  Part 2:
[[4 5 6 7]]
  Part 3:
[[ 8  9 10 11]]
Split into 2 parts along columns:
  Part 1:
[[0 1]
 [4 5]
 [8 9]]
  Part 2:
[[ 2  3]
 [ 6  7]
 [10 11]]

11. Broadcasting examples
Array:
[[1 2 3]
 [4 5 6]]
Array + scalar (10):
[[11 12 13]
 [14 15 16]]
2D array:
[[1 2 3]
 [4 5 6]]
1D array: [10 20 30]
2D + 1D (broadcasting):
[[11 22 33]
 [14 25 36]]
Column vector:
[[1]
 [2]
 [3]]
Row vector: [10 20]
Broadcasting result:
[[11 21]
 [12 22]
 [13 23]]

12. Linear algebra operations
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
A · B (dot pr

In [39]:
# NUMPY QUESTIONS 13-17: Random Numbers, Sorting, and Memory

print("="*70)
print("NUMPY QUESTIONS 13-17: Random Numbers, Sorting, and Memory")
print("="*70)

# Question 13: Random number generation
print("\n13. Random number generation")

# Set seed for reproducibility
np.random.seed(42)

# Different random distributions
uniform = np.random.uniform(0, 1, 5)
normal = np.random.normal(0, 1, 5)
integers = np.random.randint(1, 10, 5)
print(f"Uniform random [0,1): {uniform}")
print(f"Normal distribution: {normal}")
print(f"Random integers [1,10): {integers}")

# Random choice from array
choices = np.random.choice(['A', 'B', 'C'], size=5, p=[0.5, 0.3, 0.2])
print(f"Random choices with probabilities: {choices}")

# Shuffle array
arr_to_shuffle = np.arange(10)
np.random.shuffle(arr_to_shuffle)
print(f"Shuffled array: {arr_to_shuffle}")

# Question 14: Array sorting and searching
print("\n14. Array sorting and searching")

unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(f"Unsorted array: {unsorted}")

# Sorting
sorted_arr = np.sort(unsorted)
print(f"Sorted array: {sorted_arr}")

# Argsort (indices that would sort the array)
sort_indices = np.argsort(unsorted)
print(f"Sort indices: {sort_indices}")
print(f"Array sorted using indices: {unsorted[sort_indices]}")

# Searching
search_value = 5
index = np.where(unsorted == search_value)
print(f"Indices where value is {search_value}: {index[0]}")

# Unique values
unique_vals, counts = np.unique(unsorted, return_counts=True)
print(f"Unique values: {unique_vals}")
print(f"Counts: {counts}")

# Question 15: Array comparison and logical operations
print("\n15. Array comparison and logical operations")

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 0, 3, 7, 2])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")

# Element-wise comparison
print(f"arr1 == arr2: {arr1 == arr2}")
print(f"arr1 > arr2: {arr1 > arr2}")
print(f"arr1 >= 3: {arr1 >= 3}")

# Logical operations
print(f"Logical AND: {np.logical_and(arr1 > 2, arr1 < 5)}")
print(f"Logical OR: {np.logical_or(arr1 < 2, arr1 > 4)}")
print(f"Logical NOT: {np.logical_not(arr1 > 3)}")

# All and any
print(f"All elements > 0: {np.all(arr1 > 0)}")
print(f"Any element > 4: {np.any(arr1 > 4)}")

# Question 16: Advanced indexing
print("\n16. Advanced indexing")

# Fancy indexing
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(f"Original array: {arr}")
print(f"Fancy indexing with {indices}: {arr[indices]}")

# 2D fancy indexing
arr_2d = np.arange(12).reshape(3, 4)
row_indices = [0, 2]
col_indices = [1, 3]
print(f"2D array:\n{arr_2d}")
print(f"Elements at (0,1) and (2,3): {arr_2d[row_indices, col_indices]}")

# Boolean indexing with multiple conditions
complex_condition = (arr > 15) & (arr < 45)
print(f"Elements between 15 and 45: {arr[complex_condition]}")

# Question 17: Memory layout and performance
print("\n17. Memory layout and performance")

# C-style (row-major) vs Fortran-style (column-major)
arr_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')
arr_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')

print(f"C-order array flags: C_CONTIGUOUS={arr_c.flags['C_CONTIGUOUS']}")
print(f"F-order array flags: F_CONTIGUOUS={arr_f.flags['F_CONTIGUOUS']}")

# Views vs copies
original = np.arange(10)
view = original[::2]  # Creates a view
copy = original[::2].copy()  # Creates a copy

print(f"Original: {original}")
print(f"View: {view}")
original[0] = 100  # This will affect the view but not the copy
print(f"After modifying original[0]:")
print(f"Original: {original}")
print(f"View: {view}")
print(f"Copy: {copy}")

# Memory usage
print(f"Array shape {arr_c.shape} uses {arr_c.nbytes} bytes")

print(f"\nCompleted NumPy Questions 13-17!")
print("="*70)

NUMPY QUESTIONS 13-17: Random Numbers, Sorting, and Memory

13. Random number generation
Uniform random [0,1): [0.375 0.951 0.732 0.599 0.156]
Normal distribution: [ 0.279  1.011 -0.581 -0.525 -0.571]
Random integers [1,10): [6 9 1 3 7]
Random choices with probabilities: ['C' 'A' 'C' 'B' 'A']
Shuffled array: [2 6 7 4 9 5 8 0 3 1]

14. Array sorting and searching
Unsorted array: [3 1 4 1 5 9 2 6]
Sorted array: [1 1 2 3 4 5 6 9]
Sort indices: [1 3 6 0 2 4 7 5]
Array sorted using indices: [1 1 2 3 4 5 6 9]
Indices where value is 5: [4]
Unique values: [1 2 3 4 5 6 9]
Counts: [2 1 1 1 1 1 1]

15. Array comparison and logical operations
Array 1: [1 2 3 4 5]
Array 2: [1 0 3 7 2]
arr1 == arr2: [ True False  True False False]
arr1 > arr2: [False  True False False  True]
arr1 >= 3: [False False  True  True  True]
Logical AND: [False False  True  True False]
Logical OR: [ True False False False  True]
Logical NOT: [ True  True  True False False]
All elements > 0: True
Any element > 4: True

16. A

# Part 2: Pandas Series Questions (18-33)

## Pandas Series Creation, Manipulation, and Operations

A Pandas Series is a one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.). The axis labels are collectively called the index.

In [40]:
# PANDAS SERIES QUESTIONS 18-21: Creation and Basic Operations

print("="*70)
print("PANDAS SERIES QUESTIONS 18-21: Creation and Basic Operations")
print("="*70)

# Question 18: Create Series using different methods
print("\n18. Create Series using different methods")

# From list
series_from_list = pd.Series([1, 2, 3, 4, 5])
print(f"Series from list:\n{series_from_list}")

# From list with custom index
series_custom_index = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(f"\nSeries with custom index:\n{series_custom_index}")

# From dictionary
data_dict = {'apple': 5, 'banana': 3, 'orange': 8}
series_from_dict = pd.Series(data_dict)
print(f"\nSeries from dictionary:\n{series_from_dict}")

# From scalar value
series_scalar = pd.Series(100, index=['x', 'y', 'z'])
print(f"\nSeries from scalar:\n{series_scalar}")

# From NumPy array
np_array = np.array([1.1, 2.2, 3.3, 4.4])
series_from_numpy = pd.Series(np_array, index=['w', 'x', 'y', 'z'])
print(f"\nSeries from NumPy array:\n{series_from_numpy}")

# Question 19: Series indexing and selection
print("\n19. Series indexing and selection")

# Create sample series
fruits = pd.Series([5, 3, 8, 2, 6], 
                  index=['apple', 'banana', 'orange', 'grape', 'mango'])
print(f"Fruits series:\n{fruits}")

# Label-based indexing
print(f"\nApple count: {fruits['apple']}")
print(f"Multiple fruits:\n{fruits[['apple', 'orange', 'mango']]}")

# Position-based indexing
print(f"\nFirst fruit: {fruits.iloc[0]}")
print(f"First three fruits:\n{fruits.iloc[0:3]}")

# Boolean indexing
print(f"\nFruits with count > 4:\n{fruits[fruits > 4]}")

# Using .loc and .iloc
print(f"\nUsing .loc['banana':'grape']:\n{fruits.loc['banana':'grape']}")
print(f"Using .iloc[1:4]:\n{fruits.iloc[1:4]}")

# Question 20: Series operations and methods
print("\n20. Series operations and methods")

# Arithmetic operations
numbers = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(f"Original series:\n{numbers}")
print(f"Series * 2:\n{numbers * 2}")
print(f"Series + 5:\n{numbers + 5}")
print(f"Square root:\n{np.sqrt(numbers)}")

# Series with Series operations
series1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
series2 = pd.Series([4, 5, 6], index=['a', 'b', 'c'])
print(f"\nSeries 1:\n{series1}")
print(f"Series 2:\n{series2}")
print(f"Addition:\n{series1 + series2}")
print(f"Multiplication:\n{series1 * series2}")

# Question 21: Series statistical methods
print("\n21. Series statistical methods")

data = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Data series: {data.values}")

# Basic statistics
print(f"Mean: {data.mean():.2f}")
print(f"Median: {data.median()}")
print(f"Standard deviation: {data.std():.2f}")
print(f"Variance: {data.var():.2f}")
print(f"Minimum: {data.min()}")
print(f"Maximum: {data.max()}")
print(f"Sum: {data.sum()}")
print(f"Count: {data.count()}")

# Describe method
print(f"\nDescriptive statistics:\n{data.describe()}")

# Quantiles
print(f"\n25th percentile: {data.quantile(0.25)}")
print(f"75th percentile: {data.quantile(0.75)}")

print(f"\nCompleted Pandas Series Questions 18-21!")
print("="*70)

PANDAS SERIES QUESTIONS 18-21: Creation and Basic Operations

18. Create Series using different methods
Series from list:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Series with custom index:
a    10
b    20
c    30
dtype: int64

Series from dictionary:
apple     5
banana    3
orange    8
dtype: int64

Series from scalar:
x    100
y    100
z    100
dtype: int64

Series from NumPy array:
w    1.1
x    2.2
y    3.3
z    4.4
dtype: float64

19. Series indexing and selection
Fruits series:
apple     5
banana    3
orange    8
grape     2
mango     6
dtype: int64

Apple count: 5
Multiple fruits:
apple     5
orange    8
mango     6
dtype: int64

First fruit: 5
First three fruits:
apple     5
banana    3
orange    8
dtype: int64

Fruits with count > 4:
apple     5
orange    8
mango     6
dtype: int64

Using .loc['banana':'grape']:
banana    3
orange    8
grape     2
dtype: int64
Using .iloc[1:4]:
banana    3
orange    8
grape     2
dtype: int64

20. Series operations and methods
Original 

In [41]:
# PANDAS SERIES QUESTIONS 22-25: Missing Values and String Operations

print("="*70)
print("PANDAS SERIES QUESTIONS 22-25: Missing Values and String Operations")
print("="*70)

# Question 22: Handling missing values in Series
print("\n22. Handling missing values in Series")

# Create series with missing values
data_with_nan = pd.Series([1, 2, np.nan, 4, 5, np.nan, 7])
print(f"Series with NaN values:\n{data_with_nan}")

# Check for missing values
print(f"Is null:\n{data_with_nan.isnull()}")
print(f"Not null:\n{data_with_nan.notnull()}")
print(f"Number of missing values: {data_with_nan.isnull().sum()}")

# Drop missing values
cleaned_series = data_with_nan.dropna()
print(f"After dropping NaN:\n{cleaned_series}")

# Fill missing values
filled_with_zero = data_with_nan.fillna(0)
print(f"Filled with 0:\n{filled_with_zero}")

filled_with_mean = data_with_nan.fillna(data_with_nan.mean())
print(f"Filled with mean:\n{filled_with_mean}")

# Forward fill and backward fill
data_time = pd.Series([1, np.nan, np.nan, 4, np.nan, 6])
print(f"Original: {data_time.values}")
print(f"Forward fill: {data_time.fillna(method='ffill').values}")
print(f"Backward fill: {data_time.fillna(method='bfill').values}")

# Question 23: Series string operations
print("\n23. Series string operations")

# Create series with string data
names = pd.Series(['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'Diana Prince'])
print(f"Names series:\n{names}")

# String methods
print(f"Uppercase:\n{names.str.upper()}")
print(f"Lowercase:\n{names.str.lower()}")
print(f"Length of each name:\n{names.str.len()}")

# String splitting
print(f"Split names:\n{names.str.split()}")
print(f"First names:\n{names.str.split().str[0]}")
print(f"Last names:\n{names.str.split().str[1]}")

# String contains
print(f"Names containing 'o':\n{names[names.str.contains('o')]}")

# String replacement
print(f"Replace 'o' with '0':\n{names.str.replace('o', '0')}")

# Extract using regex
print(f"Extract first name:\n{names.str.extract(r'(\w+)')}")

# Question 24: Series sorting and ranking
print("\n24. Series sorting and ranking")

# Create unsorted series
grades = pd.Series([85, 92, 78, 95, 88], 
                  index=['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])
print(f"Grades:\n{grades}")

# Sort by values
sorted_by_values = grades.sort_values()
print(f"Sorted by values (ascending):\n{sorted_by_values}")

sorted_desc = grades.sort_values(ascending=False)
print(f"Sorted by values (descending):\n{sorted_desc}")

# Sort by index
sorted_by_index = grades.sort_index()
print(f"Sorted by index:\n{sorted_by_index}")

# Ranking
print(f"Rank (default):\n{grades.rank()}")
print(f"Rank (dense method):\n{grades.rank(method='dense')}")

# Question 25: Series grouping and aggregation
print("\n25. Series grouping and aggregation")

# Create series with categorical data
categories = pd.Series(['A', 'B', 'A', 'C', 'B', 'A', 'C'])
values = pd.Series([10, 20, 15, 30, 25, 12, 35])
print(f"Categories: {categories.values}")
print(f"Values: {values.values}")

# Group by categories and aggregate
grouped = values.groupby(categories).sum()
print(f"Sum by category:\n{grouped}")

grouped_mean = values.groupby(categories).mean()
print(f"Mean by category:\n{grouped_mean}")

grouped_count = values.groupby(categories).count()
print(f"Count by category:\n{grouped_count}")

# Multiple aggregations
grouped_agg = values.groupby(categories).agg(['sum', 'mean', 'count'])
print(f"Multiple aggregations:\n{grouped_agg}")

print(f"\nCompleted Pandas Series Questions 22-25!")
print("="*70)

PANDAS SERIES QUESTIONS 22-25: Missing Values and String Operations

22. Handling missing values in Series
Series with NaN values:
0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
6    7.0
dtype: float64
Is null:
0    False
1    False
2     True
3    False
4    False
5     True
6    False
dtype: bool
Not null:
0     True
1     True
2    False
3     True
4     True
5    False
6     True
dtype: bool
Number of missing values: 2
After dropping NaN:
0    1.0
1    2.0
3    4.0
4    5.0
6    7.0
dtype: float64
Filled with 0:
0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
5    0.0
6    7.0
dtype: float64
Filled with mean:
0    1.0
1    2.0
2    3.8
3    4.0
4    5.0
5    3.8
6    7.0
dtype: float64
Original: [ 1. nan nan  4. nan  6.]
Forward fill: [1. 1. 1. 4. 4. 6.]
Backward fill: [1. 4. 4. 4. 6. 6.]

23. Series string operations
Names series:
0    Alice Johnson
1        Bob Smith
2    Charlie Brown
3     Diana Prince
dtype: object
Uppercase:
0    ALICE JOHNSON
1        BOB SMITH
2    CHAR

In [42]:
# PANDAS SERIES QUESTIONS 26-29: Time Series and Advanced Operations

print("="*70)
print("PANDAS SERIES QUESTIONS 26-29: Time Series and Advanced Operations")
print("="*70)

# Question 26: Series time series operations
print("\n26. Series time series operations")

# Create date range
date_range = pd.date_range('2024-01-01', periods=10, freq='D')
ts_data = pd.Series(np.random.randn(10), index=date_range)
print(f"Time series data:\n{ts_data}")

# Time-based indexing
print(f"Data for 2024-01-05:\n{ts_data['2024-01-05']}")
print(f"Data for January 2024:\n{ts_data['2024-01']}")

# Resampling (if we had more data)
weekly_data = pd.Series(np.random.randn(30), 
                       index=pd.date_range('2024-01-01', periods=30, freq='D'))
weekly_mean = weekly_data.resample('W').mean()
print(f"Weekly averages:\n{weekly_mean}")

# Shifting
shifted = ts_data.shift(1)
print(f"Shifted by 1 period:\n{shifted.head()}")

# Question 27: Series categorical operations
print("\n27. Series categorical operations")

# Create categorical series
sizes = pd.Series(['S', 'M', 'L', 'M', 'S', 'L', 'XL', 'M'], dtype='category')
print(f"Sizes (categorical):\n{sizes}")
print(f"Categories: {sizes.cat.categories}")

# Add categories
sizes = sizes.cat.add_categories(['XS', 'XXL'])
print(f"After adding categories: {sizes.cat.categories}")

# Reorder categories
sizes = sizes.cat.reorder_categories(['XS', 'S', 'M', 'L', 'XL', 'XXL'], ordered=True)
print(f"Ordered categories:\n{sizes}")

# Value counts for categories
print(f"Value counts:\n{sizes.value_counts()}")

# Question 28: Series groupby operations
print("\n28. Series groupby operations")

# Create series with repeated index values
data = pd.Series([1, 2, 3, 4, 5, 6, 7, 8], 
                index=['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D'])
print(f"Data with repeated indices:\n{data}")

# Group by index and aggregate
grouped = data.groupby(level=0).sum()
print(f"Sum by group:\n{grouped}")

# Other aggregations
print(f"Mean by group:\n{data.groupby(level=0).mean()}")
print(f"Count by group:\n{data.groupby(level=0).count()}")

# Group by values
categories = pd.Series(['low', 'low', 'high', 'high', 'medium', 'low', 'high', 'medium'])
values = pd.Series([10, 15, 30, 25, 20, 12, 35, 18])
grouped_by_category = values.groupby(categories).mean()
print(f"Mean values by category:\n{grouped_by_category}")

# Question 29: Series unique values and duplicates
print("\n29. Series unique values and duplicates")

# Series with duplicates
data_with_dups = pd.Series([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
print(f"Data with duplicates: {data_with_dups.values}")

# Unique values
unique_vals = data_with_dups.unique()
print(f"Unique values: {unique_vals}")
print(f"Number of unique values: {data_with_dups.nunique()}")

# Value counts
value_counts = data_with_dups.value_counts()
print(f"Value counts:\n{value_counts}")

# Duplicated values
print(f"Duplicated (first occurrence):\n{data_with_dups.duplicated()}")
print(f"Duplicated (last occurrence):\n{data_with_dups.duplicated(keep='last')}")

# Drop duplicates
no_dups = data_with_dups.drop_duplicates()
print(f"After dropping duplicates: {no_dups.values}")

print(f"\nCompleted Pandas Series Questions 26-29!")
print("="*70)

PANDAS SERIES QUESTIONS 26-29: Time Series and Advanced Operations

26. Series time series operations
Time series data:
2024-01-01   -0.924083
2024-01-02    0.291034
2024-01-03   -0.635560
2024-01-04   -1.021552
2024-01-05   -0.161755
2024-01-06   -0.533649
2024-01-07   -0.005528
2024-01-08   -0.229450
2024-01-09    0.389349
2024-01-10   -1.265119
Freq: D, dtype: float64
Data for 2024-01-05:
-0.16175538639752096
Data for January 2024:
2024-01-01   -0.924083
2024-01-02    0.291034
2024-01-03   -0.635560
2024-01-04   -1.021552
2024-01-05   -0.161755
2024-01-06   -0.533649
2024-01-07   -0.005528
2024-01-08   -0.229450
2024-01-09    0.389349
2024-01-10   -1.265119
Freq: D, dtype: float64
Weekly averages:
2024-01-07    0.510281
2024-01-14   -0.343673
2024-01-21    0.185418
2024-01-28   -0.030440
2024-02-04    0.448580
Freq: W-SUN, dtype: float64
Shifted by 1 period:
2024-01-01         NaN
2024-01-02   -0.924083
2024-01-03    0.291034
2024-01-04   -0.635560
2024-01-05   -1.021552
Freq: D, dt

In [43]:
# PANDAS SERIES QUESTIONS 30-33: Mathematical Functions and Performance

print("="*70)
print("PANDAS SERIES QUESTIONS 30-33: Mathematical Functions and Performance")
print("="*70)

# Question 30: Series mathematical functions
print("\n30. Series mathematical functions")

# Create series for math operations
math_data = pd.Series([1, 4, 9, 16, 25])
print(f"Math data: {math_data.values}")

# Basic math functions
print(f"Square root: {np.sqrt(math_data).values}")
print(f"Logarithm: {np.log(math_data).values}")
print(f"Exponential: {np.exp(math_data).head(3).values}")  # Only first 3 to avoid large numbers

# Trigonometric functions
angles = pd.Series([0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi])
print(f"Angles: {angles.values}")
print(f"Sine: {np.sin(angles).values}")
print(f"Cosine: {np.cos(angles).values}")

# Cumulative operations
data = pd.Series([1, 2, 3, 4, 5])
print(f"Original: {data.values}")
print(f"Cumulative sum: {data.cumsum().values}")
print(f"Cumulative product: {data.cumprod().values}")
print(f"Cumulative min: {data.cummin().values}")
print(f"Cumulative max: {data.cummax().values}")

# Question 31: Series comparison and alignment
print("\n31. Series comparison and alignment")

# Create two series with different indices
series_a = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
series_b = pd.Series([4, 5, 6, 7], index=['a', 'b', 'd', 'e'])
print(f"Series A:\n{series_a}")
print(f"Series B:\n{series_b}")

# Alignment in operations (NaN for missing indices)
result = series_a + series_b
print(f"A + B (with alignment):\n{result}")

# Fill value for missing indices
result_filled = series_a.add(series_b, fill_value=0)
print(f"A + B (fill missing with 0):\n{result_filled}")

# Comparison operations
series1 = pd.Series([1, 2, 3, 4])
series2 = pd.Series([1, 3, 2, 4])
print(f"Series 1: {series1.values}")
print(f"Series 2: {series2.values}")
print(f"Equal: {(series1 == series2).values}")
print(f"Greater: {(series1 > series2).values}")

# Question 32: Series indexing with MultiIndex
print("\n32. Series indexing with MultiIndex")

# Create MultiIndex series
arrays = [['A', 'A', 'B', 'B'], ['one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=['first', 'second'])
multi_series = pd.Series([1, 2, 3, 4], index=index)
print(f"MultiIndex series:\n{multi_series}")

# Access by level
print(f"Level 'A':\n{multi_series['A']}")
print(f"Level 'B', 'one': {multi_series['B', 'one']}")

# Unstack to DataFrame
unstacked = multi_series.unstack()
print(f"Unstacked to DataFrame:\n{unstacked}")

# Stack back to Series
stacked_back = unstacked.stack()
print(f"Stacked back:\n{stacked_back}")

# Question 33: Series performance and memory optimization
print("\n33. Series performance and memory optimization")

# Memory usage comparison
large_int_series = pd.Series(range(100), dtype='int64')
small_int_series = pd.Series(range(100), dtype='int8')

print(f"int64 series memory usage: {large_int_series.memory_usage(deep=True)} bytes")
print(f"int8 series memory usage: {small_int_series.memory_usage(deep=True)} bytes")

# Category vs object for strings
string_series = pd.Series(['A', 'B', 'C'] * 1000)
category_series = pd.Series(['A', 'B', 'C'] * 1000, dtype='category')

print(f"String series memory: {string_series.memory_usage(deep=True)} bytes")
print(f"Category series memory: {category_series.memory_usage(deep=True)} bytes")

# Info about series
print(f"\nString series info:")
print(f"  dtype: {string_series.dtype}")
print(f"  shape: {string_series.shape}")

print(f"\nCategory series info:")
print(f"  dtype: {category_series.dtype}")
print(f"  categories: {category_series.cat.categories}")

# Conversion between types
converted_to_category = string_series.astype('category')
print(f"Converted to category memory: {converted_to_category.memory_usage(deep=True)} bytes")

print(f"\nCompleted Pandas Series Questions 30-33!")
print("="*70)

PANDAS SERIES QUESTIONS 30-33: Mathematical Functions and Performance

30. Series mathematical functions
Math data: [ 1  4  9 16 25]
Square root: [1. 2. 3. 4. 5.]
Logarithm: [0.    1.386 2.197 2.773 3.219]
Exponential: [   2.718   54.598 8103.084]
Angles: [0.    0.785 1.571 2.356 3.142]
Sine: [0.    0.707 1.    0.707 0.   ]
Cosine: [ 1.     0.707  0.    -0.707 -1.   ]
Original: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]
Cumulative min: [1 1 1 1 1]
Cumulative max: [1 2 3 4 5]

31. Series comparison and alignment
Series A:
a    1
b    2
c    3
dtype: int64
Series B:
a    4
b    5
d    6
e    7
dtype: int64
A + B (with alignment):
a    5.0
b    7.0
c    NaN
d    NaN
e    NaN
dtype: float64
A + B (fill missing with 0):
a    5.0
b    7.0
c    3.0
d    6.0
e    7.0
dtype: float64
Series 1: [1 2 3 4]
Series 2: [1 3 2 4]
Equal: [ True False False  True]
Greater: [False False  True False]

32. Series indexing with MultiIndex
MultiIndex series:
first  

# Part 3: Pandas DataFrame Questions (34-50)

## Pandas DataFrame Creation, Manipulation, and Analysis

A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. It is generally the most commonly used pandas object and can be thought of as a dict-like container for Series objects.

In [44]:
# PANDAS DATAFRAME QUESTIONS 34-37: Creation and Basic Operations

print("="*70)
print("PANDAS DATAFRAME QUESTIONS 34-37: Creation and Basic Operations")
print("="*70)

# Question 34: Create DataFrames using different methods
print("\n34. Create DataFrames using different methods")

# From dictionary
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}
df_from_dict = pd.DataFrame(data_dict)
print("DataFrame from dictionary:")
print(df_from_dict)

# From list of dictionaries
list_of_dicts = [
    {'Product': 'A', 'Price': 10, 'Quantity': 100},
    {'Product': 'B', 'Price': 15, 'Quantity': 80},
    {'Product': 'C', 'Price': 20, 'Quantity': 60}
]
df_from_list = pd.DataFrame(list_of_dicts)
print(f"\nDataFrame from list of dictionaries:")
print(df_from_list)

# From NumPy array
np_data = np.random.randint(1, 100, size=(4, 3))
df_from_numpy = pd.DataFrame(np_data, 
                            columns=['Col1', 'Col2', 'Col3'],
                            index=['Row1', 'Row2', 'Row3', 'Row4'])
print(f"\nDataFrame from NumPy array:")
print(df_from_numpy)

# From Series
series1 = pd.Series([1, 2, 3], name='A')
series2 = pd.Series([4, 5, 6], name='B')
df_from_series = pd.DataFrame([series1, series2]).T
print(f"\nDataFrame from Series:")
print(df_from_series)

# Question 35: DataFrame indexing and selection
print("\n35. DataFrame indexing and selection")

# Use the employee data for examples
employees = df_from_dict.copy()
print("Employee DataFrame:")
print(employees)

# Select single column (returns Series)
names = employees['Name']
print(f"\nNames column (Series):\n{names}")

# Select multiple columns (returns DataFrame)
name_age = employees[['Name', 'Age']]
print(f"\nName and Age columns:")
print(name_age)

# Row selection using iloc
print(f"\nFirst row using iloc:")
print(employees.iloc[0])

# Row selection using loc (by index)
print(f"\nFirst row using loc:")
print(employees.loc[0])

# Select specific cells
print(f"\nAge of second employee: {employees.loc[1, 'Age']}")
print(f"Using iloc: {employees.iloc[1, 1]}")  # Same result

# Boolean indexing
high_salary = employees[employees['Salary'] > 55000]
print(f"\nEmployees with salary > 55000:")
print(high_salary)

# Question 36: DataFrame operations and methods
print("\n36. DataFrame operations and methods")

# Create sample data for operations
sales_data = pd.DataFrame({
    'Product': ['A', 'B', 'C', 'D'],
    'Q1': [100, 150, 200, 120],
    'Q2': [110, 160, 190, 130],
    'Q3': [120, 140, 210, 140],
    'Q4': [130, 170, 220, 150]
})
print("Sales data:")
print(sales_data)

# Basic info about DataFrame
print(f"\nDataFrame shape: {sales_data.shape}")
print(f"Columns: {list(sales_data.columns)}")
print(f"Index: {list(sales_data.index)}")
print(f"Data types:\n{sales_data.dtypes}")

# Statistical summary
numeric_data = sales_data.select_dtypes(include=[np.number])
print(f"\nStatistical summary:")
print(numeric_data.describe())

# Row and column operations
sales_data['Total'] = sales_data[['Q1', 'Q2', 'Q3', 'Q4']].sum(axis=1)
print(f"\nAfter adding Total column:")
print(sales_data)

# Question 37: DataFrame missing data handling
print("\n37. DataFrame missing data handling")

# Create DataFrame with missing values
data_with_missing = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, np.nan],
    'C': [1, 2, 3, np.nan, 5],
    'D': [1, np.nan, np.nan, 4, 5]
})
print("DataFrame with missing values:")
print(data_with_missing)

# Check for missing values
print(f"\nMissing values per column:")
print(data_with_missing.isnull().sum())

print(f"\nTotal missing values: {data_with_missing.isnull().sum().sum()}")

# Drop rows/columns with missing values
print(f"\nDrop rows with any NaN:")
print(data_with_missing.dropna())

print(f"\nDrop columns with any NaN:")
print(data_with_missing.dropna(axis=1))

# Fill missing values
print(f"\nFill NaN with 0:")
print(data_with_missing.fillna(0))

# Fill with column means
filled_with_mean = data_with_missing.fillna(data_with_missing.mean())
print(f"\nFill NaN with column means:")
print(filled_with_mean)

print(f"\nCompleted DataFrame Questions 34-37!")
print("="*70)

PANDAS DATAFRAME QUESTIONS 34-37: Creation and Basic Operations

34. Create DataFrames using different methods
DataFrame from dictionary:
      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

DataFrame from list of dictionaries:
  Product  Price  Quantity
0       A     10       100
1       B     15        80
2       C     20        60

DataFrame from NumPy array:
      Col1  Col2  Col3
Row1    90    14    27
Row2     9    79    15
Row3    90    42    77
Row4    51    63    96

DataFrame from Series:
   A  B
0  1  4
1  2  5
2  3  6

35. DataFrame indexing and selection
Employee DataFrame:
      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

Names column (Series):
0      Alice
1        Bob
2    Charlie
3      Diana
Name: Name, dtype: object

Name and Age co

In [45]:
# PANDAS DATAFRAME QUESTIONS 38-42: Sorting, Grouping, and Merging

print("="*70)
print("PANDAS DATAFRAME QUESTIONS 38-42: Sorting, Grouping, and Merging")
print("="*70)

# Question 38: DataFrame sorting and ranking
print("\n38. DataFrame sorting and ranking")

# Create student grades data
students = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Math': [85, 92, 78, 95, 88],
    'Science': [90, 85, 92, 88, 94],
    'English': [88, 90, 85, 92, 87]
})
print("Student grades:")
print(students)

# Sort by single column
sorted_by_math = students.sort_values('Math')
print(f"\nSorted by Math (ascending):")
print(sorted_by_math)

# Sort by multiple columns
sorted_multi = students.sort_values(['Science', 'Math'], ascending=[False, True])
print(f"\nSorted by Science (desc) then Math (asc):")
print(sorted_multi)

# Sort by index
students_reindexed = students.set_index('Name')
sorted_by_index = students_reindexed.sort_index()
print(f"\nSorted by index (Name):")
print(sorted_by_index)

# Ranking
students['Math_Rank'] = students['Math'].rank(ascending=False)
print(f"\nWith Math ranking:")
print(students[['Name', 'Math', 'Math_Rank']])

# Question 39: DataFrame groupby operations
print("\n39. DataFrame groupby operations")

# Create sales data with categories
sales = pd.DataFrame({
    'Region': ['North', 'South', 'North', 'South', 'East', 'East', 'West', 'West'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 120, 180, 90, 160, 140],
    'Profit': [20, 30, 40, 25, 35, 18, 32, 28]
})
print("Sales data:")
print(sales)

# Group by single column
region_sales = sales.groupby('Region').sum()
print(f"\nSales by Region:")
print(region_sales)

# Group by multiple columns
region_product = sales.groupby(['Region', 'Product']).sum()
print(f"\nSales by Region and Product:")
print(region_product)

# Multiple aggregations
agg_results = sales.groupby('Region').agg({
    'Sales': ['sum', 'mean', 'count'],
    'Profit': ['sum', 'mean']
})
print(f"\nMultiple aggregations by Region:")
print(agg_results)

# Custom aggregation function
def profit_margin(group):
    return (group['Profit'].sum() / group['Sales'].sum()) * 100

margin_by_region = sales.groupby('Region').apply(profit_margin)
print(f"\nProfit margin by Region:")
print(margin_by_region)

# Question 40: DataFrame merging and joining
print("\n40. DataFrame merging and joining")

# Create two DataFrames for merging
customers = pd.DataFrame({
    'CustomerID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'City': ['NY', 'LA', 'Chicago', 'Miami']
})

orders = pd.DataFrame({
    'OrderID': [101, 102, 103, 104, 105],
    'CustomerID': [1, 2, 2, 3, 5],
    'Product': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    'Amount': [1000, 500, 300, 400, 100]
})

print("Customers DataFrame:")
print(customers)
print("\nOrders DataFrame:")
print(orders)

# Inner join
inner_join = pd.merge(customers, orders, on='CustomerID', how='inner')
print(f"\nInner Join:")
print(inner_join)

# Left join
left_join = pd.merge(customers, orders, on='CustomerID', how='left')
print(f"\nLeft Join:")
print(left_join)

# Right join
right_join = pd.merge(customers, orders, on='CustomerID', how='right')
print(f"\nRight Join:")
print(right_join)

# Outer join
outer_join = pd.merge(customers, orders, on='CustomerID', how='outer')
print(f"\nOuter Join:")
print(outer_join)

# Question 41: DataFrame concatenation
print("\n41. DataFrame concatenation")

# Create sample DataFrames
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
df3 = pd.DataFrame({'C': [9, 10], 'D': [11, 12]})

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)
print("\nDataFrame 3:")
print(df3)

# Vertical concatenation (row-wise)
vertical_concat = pd.concat([df1, df2], axis=0)
print(f"\nVertical concatenation:")
print(vertical_concat)

# Horizontal concatenation (column-wise)
horizontal_concat = pd.concat([df1, df3], axis=1)
print(f"\nHorizontal concatenation:")
print(horizontal_concat)

# Concatenation with keys
concat_with_keys = pd.concat([df1, df2], keys=['First', 'Second'])
print(f"\nConcatenation with keys:")
print(concat_with_keys)

# Question 42: DataFrame pivot operations
print("\n42. DataFrame pivot operations")

# Create sample data for pivoting
pivot_data = pd.DataFrame({
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [100, 150, 120, 180],
    'Region': ['North', 'South', 'North', 'South']
})
print("Data for pivoting:")
print(pivot_data)

# Pivot table
pivot_table = pivot_data.pivot_table(
    values='Sales', 
    index='Date', 
    columns='Product', 
    aggfunc='sum'
)
print(f"\nPivot table (Sales by Date and Product):")
print(pivot_table)

# Pivot with multiple values
multi_pivot = pivot_data.pivot_table(
    values='Sales',
    index='Date',
    columns=['Product', 'Region'],
    aggfunc='sum'
)
print(f"\nMulti-level pivot:")
print(multi_pivot)

# Melt (unpivot)
melted = pd.melt(pivot_table.reset_index(), 
                id_vars=['Date'], 
                value_vars=['A', 'B'],
                var_name='Product', 
                value_name='Sales')
print(f"\nMelted data:")
print(melted)

print(f"\nCompleted DataFrame Questions 38-42!")
print("="*70)

PANDAS DATAFRAME QUESTIONS 38-42: Sorting, Grouping, and Merging

38. DataFrame sorting and ranking
Student grades:
      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    92       85       90
2  Charlie    78       92       85
3    Diana    95       88       92
4      Eve    88       94       87

Sorted by Math (ascending):
      Name  Math  Science  English
2  Charlie    78       92       85
0    Alice    85       90       88
4      Eve    88       94       87
1      Bob    92       85       90
3    Diana    95       88       92

Sorted by Science (desc) then Math (asc):
      Name  Math  Science  English
4      Eve    88       94       87
2  Charlie    78       92       85
0    Alice    85       90       88
3    Diana    95       88       92
1      Bob    92       85       90

Sorted by index (Name):
         Math  Science  English
Name                           
Alice      85       90       88
Bob        92       85       90
Charlie    78       92       

In [46]:
# PANDAS DATAFRAME QUESTIONS 43-46: Advanced Operations

print("="*70)
print("PANDAS DATAFRAME QUESTIONS 43-46: Advanced Operations")
print("="*70)

# Question 43: DataFrame apply and transform operations
print("\n43. DataFrame apply and transform operations")

# Create sample data
df_transform = pd.DataFrame({
    'Group': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Value1': [10, 20, 30, 40, 50, 60],
    'Value2': [1, 2, 3, 4, 5, 6]
})
print("Sample DataFrame:")
print(df_transform)

# Apply function to entire DataFrame
def add_suffix(x):
    if x.dtype == 'object':
        return x.astype(str) + '_modified'
    else:
        return x * 10

applied_df = df_transform.apply(add_suffix)
print(f"\nApply function to DataFrame:")
print(applied_df)

# Apply function to specific columns
df_transform['Value1_squared'] = df_transform['Value1'].apply(lambda x: x**2)
print(f"\nAfter applying square function to Value1:")
print(df_transform)

# Transform function (maintains original shape)
normalized = df_transform.groupby('Group')[['Value1', 'Value2']].transform(
    lambda x: (x - x.mean()) / x.std()
)
print(f"\nNormalized values by group:")
print(normalized)

# Question 44: DataFrame string operations
print("\n44. DataFrame string operations")

# Create DataFrame with text data
text_df = pd.DataFrame({
    'Names': ['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'Diana Prince'],
    'Emails': ['alice@email.com', 'bob@company.org', 'charlie@test.net', 'diana@work.gov'],
    'Phones': ['123-456-7890', '987-654-3210', '555-123-4567', '444-555-6666']
})
print("Text DataFrame:")
print(text_df)

# String operations on columns
text_df['First_Name'] = text_df['Names'].str.split().str[0]
text_df['Last_Name'] = text_df['Names'].str.split().str[1]
text_df['Email_Domain'] = text_df['Emails'].str.split('@').str[1]
text_df['Phone_Area'] = text_df['Phones'].str[:3]

print(f"\nAfter string operations:")
print(text_df)

# String filtering
gmail_users = text_df[text_df['Emails'].str.contains('email|company')]
print(f"\nUsers with 'email' or 'company' domains:")
print(gmail_users)

# Question 45: DataFrame time series operations
print("\n45. DataFrame time series operations")

# Create time series DataFrame
dates = pd.date_range('2024-01-01', periods=30, freq='D')
ts_df = pd.DataFrame({
    'Date': dates,
    'Sales': np.random.randint(100, 1000, 30),
    'Customers': np.random.randint(10, 100, 30),
    'Temperature': np.random.normal(20, 5, 30)
})
ts_df.set_index('Date', inplace=True)
print("Time series DataFrame (first 5 rows):")
print(ts_df.head())

# Resample operations
weekly_avg = ts_df.resample('W').mean()
print(f"\nWeekly averages:")
print(weekly_avg)

# Rolling window operations
ts_df['Sales_MA7'] = ts_df['Sales'].rolling(window=7).mean()
ts_df['Sales_MA3'] = ts_df['Sales'].rolling(window=3).mean()
print(f"\nWith moving averages (last 5 rows):")
print(ts_df[['Sales', 'Sales_MA3', 'Sales_MA7']].tail())

# Date-based filtering
january_data = ts_df['2024-01-15':'2024-01-20']
print(f"\nData from Jan 15-20:")
print(january_data)

# Question 46: DataFrame multi-indexing
print("\n46. DataFrame multi-indexing")

# Create MultiIndex DataFrame
arrays = [
    ['Sales', 'Sales', 'Marketing', 'Marketing'],
    ['Q1', 'Q2', 'Q1', 'Q2']
]
multi_index = pd.MultiIndex.from_arrays(arrays, names=['Department', 'Quarter'])
multi_df = pd.DataFrame({
    'Revenue': [100000, 120000, 80000, 90000],
    'Employees': [10, 12, 8, 9]
}, index=multi_index)

print("MultiIndex DataFrame:")
print(multi_df)

# Access by level
print(f"\nSales department data:")
print(multi_df.loc['Sales'])

# Cross-section
print(f"\nQ1 data across departments:")
print(multi_df.xs('Q1', level='Quarter'))

# Unstack and stack
unstacked = multi_df.unstack('Quarter')
print(f"\nUnstacked by Quarter:")
print(unstacked)

print(f"\nCompleted DataFrame Questions 43-46!")
print("="*70)

PANDAS DATAFRAME QUESTIONS 43-46: Advanced Operations

43. DataFrame apply and transform operations
Sample DataFrame:
  Group  Value1  Value2
0     A      10       1
1     A      20       2
2     B      30       3
3     B      40       4
4     C      50       5
5     C      60       6

Apply function to DataFrame:
        Group  Value1  Value2
0  A_modified     100      10
1  A_modified     200      20
2  B_modified     300      30
3  B_modified     400      40
4  C_modified     500      50
5  C_modified     600      60

After applying square function to Value1:
  Group  Value1  Value2  Value1_squared
0     A      10       1             100
1     A      20       2             400
2     B      30       3             900
3     B      40       4            1600
4     C      50       5            2500
5     C      60       6            3600

Normalized values by group:
     Value1    Value2
0 -0.707107 -0.707107
1  0.707107  0.707107
2 -0.707107 -0.707107
3  0.707107  0.707107
4 -0.707107 

In [47]:
# PANDAS DATAFRAME QUESTIONS 47-50: Statistical Analysis and Data Workflow

print("="*70)
print("PANDAS DATAFRAME QUESTIONS 47-50: Statistical Analysis and Data Workflow")
print("="*70)

# Question 47: DataFrame advanced filtering
print("\n47. DataFrame advanced filtering")

# Create sample data for filtering
filter_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'Age': [25, 35, 45, 30, 28, 40],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'IT', 'HR'],
    'Salary': [60000, 55000, 80000, 65000, 58000, 62000],
    'Experience': [2, 8, 15, 5, 3, 12]
})
print("Employee DataFrame:")
print(filter_df)

# Multiple conditions
it_experienced = filter_df[
    (filter_df['Department'] == 'IT') & 
    (filter_df['Experience'] > 2) & 
    (filter_df['Salary'] > 55000)
]
print(f"\nIT employees with >2 years experience and >55k salary:")
print(it_experienced)

# Query method
high_performers = filter_df.query('Age < 35 and Salary > 55000')
print(f"\nHigh performers under 35:")
print(high_performers)

# isin() method
selected_depts = filter_df[filter_df['Department'].isin(['IT', 'Finance'])]
print(f"\nIT and Finance departments:")
print(selected_depts)

# Question 48: DataFrame statistical operations
print("\n48. DataFrame statistical operations")

# Create numerical DataFrame
stats_df = pd.DataFrame({
    'A': np.random.normal(100, 15, 100),
    'B': np.random.normal(50, 10, 100),
    'C': np.random.exponential(2, 100),
    'D': np.random.uniform(0, 100, 100)
})

print("Statistical summary:")
print(stats_df.describe())

# Correlation matrix
correlation = stats_df.corr()
print(f"\nCorrelation matrix:")
print(correlation)

# Covariance matrix
covariance = stats_df.cov()
print(f"\nCovariance matrix:")
print(covariance.round(2))

# Percentiles
percentiles = stats_df.quantile([0.25, 0.5, 0.75, 0.9, 0.95])
print(f"\nPercentiles:")
print(percentiles)

# Skewness and kurtosis
print(f"\nSkewness:")
print(stats_df.skew())
print(f"\nKurtosis:")
print(stats_df.kurtosis())

# Question 49: DataFrame memory optimization
print("\n49. DataFrame memory optimization")

# Create DataFrame with different data types
memory_df = pd.DataFrame({
    'integers': range(1000),
    'floats': np.random.random(1000),
    'categories': np.random.choice(['A', 'B', 'C'], 1000),
    'booleans': np.random.choice([True, False], 1000),
    'dates': pd.date_range('2024-01-01', periods=1000, freq='H')
})

print("Original DataFrame info:")
print(f"Shape: {memory_df.shape}")
print(f"Memory usage:\n{memory_df.memory_usage(deep=True)}")

# Optimize data types
optimized_df = memory_df.copy()

# Convert integers to smaller type if possible
optimized_df['integers'] = pd.to_numeric(optimized_df['integers'], downcast='integer')

# Convert floats to smaller type
optimized_df['floats'] = pd.to_numeric(optimized_df['floats'], downcast='float')

# Convert strings to category
optimized_df['categories'] = optimized_df['categories'].astype('category')

print(f"\nAfter optimization:")
print(f"Memory usage:\n{optimized_df.memory_usage(deep=True)}")

# Calculate memory savings
original_memory = memory_df.memory_usage(deep=True).sum()
optimized_memory = optimized_df.memory_usage(deep=True).sum()
savings = (original_memory - optimized_memory) / original_memory * 100

print(f"\nMemory savings: {savings:.1f}%")

# Question 50: DataFrame advanced data analysis workflow
print("\n50. DataFrame advanced data analysis workflow")

# Create comprehensive dataset
np.random.seed(42)
analysis_df = pd.DataFrame({
    'customer_id': range(1, 1001),
    'age': np.random.randint(18, 80, 1000),
    'gender': np.random.choice(['M', 'F'], 1000),
    'city': np.random.choice(['NYC', 'LA', 'Chicago', 'Houston', 'Phoenix'], 1000),
    'purchase_amount': np.random.exponential(50, 1000),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Home'], 1000),
    'satisfaction_score': np.random.randint(1, 6, 1000),
    'purchase_date': pd.date_range('2024-01-01', periods=1000, freq='H')
})

print("Sample of analysis dataset:")
print(analysis_df.head())

# Data quality check
print(f"\nData Quality Check:")
print(f"Shape: {analysis_df.shape}")
print(f"Missing values:\n{analysis_df.isnull().sum()}")
print(f"Duplicates: {analysis_df.duplicated().sum()}")

# Descriptive statistics by group
print(f"\nPurchase amount by product category:")
category_stats = analysis_df.groupby('product_category')['purchase_amount'].agg([
    'count', 'mean', 'median', 'std', 'min', 'max'
]).round(2)
print(category_stats)

# Advanced analysis: Customer segmentation
analysis_df['age_group'] = pd.cut(analysis_df['age'], 
                                 bins=[0, 30, 50, 100], 
                                 labels=['Young', 'Middle', 'Senior'])

# Customer value segmentation
analysis_df['customer_value'] = pd.qcut(analysis_df['purchase_amount'], 
                                       q=3, 
                                       labels=['Low', 'Medium', 'High'])

# Cross-tabulation analysis
crosstab = pd.crosstab(analysis_df['age_group'], 
                      analysis_df['customer_value'], 
                      normalize='index') * 100
print(f"\nCustomer value distribution by age group (%):")
print(crosstab.round(1))

# Time series analysis
analysis_df['purchase_month'] = analysis_df['purchase_date'].dt.to_period('M')
monthly_sales = analysis_df.groupby('purchase_month').agg({
    'purchase_amount': ['sum', 'count', 'mean']
}).round(2)
print(f"\nMonthly sales summary:")
print(monthly_sales.head())

# Statistical testing example: Gender differences in satisfaction
male_satisfaction = analysis_df[analysis_df['gender'] == 'M']['satisfaction_score']
female_satisfaction = analysis_df[analysis_df['gender'] == 'F']['satisfaction_score']

print(f"\nSatisfaction score by gender:")
print(f"Male - Mean: {male_satisfaction.mean():.2f}, Std: {male_satisfaction.std():.2f}")
print(f"Female - Mean: {female_satisfaction.mean():.2f}, Std: {female_satisfaction.std():.2f}")

# Summary report
print(f"\n" + "="*50)
print("COMPREHENSIVE DATA ANALYSIS COMPLETE")
print("="*50)
print(f"Dataset analyzed: {analysis_df.shape[0]} customers, {analysis_df.shape[1]} features")
print(f"Key insights:")
print(f"- Top category: {analysis_df['product_category'].value_counts().index[0]}")
print(f"- Average purchase: ${analysis_df['purchase_amount'].mean():.2f}")
print(f"- Average satisfaction: {analysis_df['satisfaction_score'].mean():.1f}/5")
print(f"- Age range: {analysis_df['age'].min()}-{analysis_df['age'].max()} years")

print(f"\nCompleted DataFrame Questions 47-50!")
print("="*70)

print(f"\n🎉 CONGRATULATIONS! 🎉")
print("="*70)
print("You have successfully completed all 50 NumPy, Pandas Series, and DataFrame questions!")
print("\nSkills covered:")
print("✅ NumPy array operations and mathematical functions")
print("✅ Pandas Series creation, manipulation, and analysis")
print("✅ DataFrame operations, merging, and grouping")
print("✅ Statistical analysis and data visualization preparation")
print("✅ Memory optimization and performance considerations")
print("✅ Real-world data analysis workflows")
print("\nYou're now well-equipped for data science projects!")
print("="*70)

PANDAS DATAFRAME QUESTIONS 47-50: Statistical Analysis and Data Workflow

47. DataFrame advanced filtering
Employee DataFrame:
      Name  Age Department  Salary  Experience
0    Alice   25         IT   60000           2
1      Bob   35         HR   55000           8
2  Charlie   45         IT   80000          15
3    Diana   30    Finance   65000           5
4      Eve   28         IT   58000           3
5    Frank   40         HR   62000          12

IT employees with >2 years experience and >55k salary:
      Name  Age Department  Salary  Experience
2  Charlie   45         IT   80000          15
4      Eve   28         IT   58000           3

High performers under 35:
    Name  Age Department  Salary  Experience
0  Alice   25         IT   60000           2
3  Diana   30    Finance   65000           5
4    Eve   28         IT   58000           3

IT and Finance departments:
      Name  Age Department  Salary  Experience
0    Alice   25         IT   60000           2
2  Charlie   45  