# 🔍 NumPy Indexing and Slicing Guide

NumPy provides powerful and flexible ways to access and manipulate array elements through indexing and slicing operations. Understanding these concepts is crucial for efficient data manipulation and analysis.

## 📋 Indexing and Slicing Overview

| Operation | Syntax | Description | Example |
|-----------|--------|-------------|---------|
| **Basic Indexing** | `arr[i]` | Access single element | `arr[0]` |
| **Negative Indexing** | `arr[-i]` | Access from end | `arr[-1]` |
| **Basic Slicing** | `arr[start:stop:step]` | Extract subsequence | `arr[1:5:2]` |
| **Multi-dimensional** | `arr[i, j]` | Access 2D element | `arr[0, 1]` |
| **Boolean Indexing** | `arr[condition]` | Filter by condition | `arr[arr > 5]` |
| **Fancy Indexing** | `arr[[i, j, k]]` | Select specific indices | `arr[[0, 2, 4]]` |

## 🎯 Key Concepts

### **🔢 Indexing vs Slicing**
- **Indexing**: Returns a single element or reduces dimensionality
- **Slicing**: Returns a view of the original array (same dimensionality)

### **👁️ Views vs Copies**
- **Views**: Share memory with original array (slicing creates views)
- **Copies**: Independent memory (fancy indexing creates copies)

### **🧭 Coordinate System**
- **0-based indexing**: First element is at index 0
- **Negative indexing**: -1 refers to last element
- **Multi-dimensional**: Use comma-separated indices `[row, col]`

## ⚡ Performance Tips

1. **Use slicing over loops** for better performance
2. **Boolean indexing** is very efficient for filtering
3. **Views are faster** than copies (when possible)
4. **Vectorized operations** work well with sliced arrays
5. **Avoid creating unnecessary copies** in memory-constrained environments

In [ ]:
# =============================================================================
# 🔍 NUMPY INDEXING AND SLICING - COMPREHENSIVE EXAMPLES
# =============================================================================

import numpy as np

print("🔍 NumPy Indexing and Slicing Demonstration")
print("=" * 60)

# =============================================================================
# 1️⃣ BASIC INDEXING - Single Elements
# =============================================================================

print("\n1️⃣ Basic Indexing - Single Elements")
print("-" * 45)

# Create a 1D array
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(f"Array: {arr_1d}")
print(f"Indices: {list(range(len(arr_1d)))}")

# Positive indexing (from start)
print(f"\nPositive indexing:")
print(f"arr[0] = {arr_1d[0]} (first element)")
print(f"arr[3] = {arr_1d[3]} (fourth element)")
print(f"arr[8] = {arr_1d[8]} (last element)")

# Negative indexing (from end)
print(f"\nNegative indexing:")
print(f"arr[-1] = {arr_1d[-1]} (last element)")
print(f"arr[-2] = {arr_1d[-2]} (second-to-last)")
print(f"arr[-9] = {arr_1d[-9]} (first element)")

# =============================================================================
# 2️⃣ BASIC SLICING - Ranges of Elements
# =============================================================================

print("\n2️⃣ Basic Slicing - Ranges of Elements")
print("-" * 45)

print(f"Original array: {arr_1d}")

# Basic slicing syntax: array[start:stop:step]
print(f"\nBasic slicing examples:")
print(f"arr[1:5] = {arr_1d[1:5]} (elements 1 to 4)")
print(f"arr[2:7] = {arr_1d[2:7]} (elements 2 to 6)")
print(f"arr[:4] = {arr_1d[:4]} (first 4 elements)")
print(f"arr[5:] = {arr_1d[5:]} (from element 5 to end)")
print(f"arr[:] = {arr_1d[:]} (entire array)")

# Step parameter
print(f"\nWith step parameter:")
print(f"arr[::2] = {arr_1d[::2]} (every 2nd element)")
print(f"arr[1::2] = {arr_1d[1::2]} (every 2nd, starting at 1)")
print(f"arr[::3] = {arr_1d[::3]} (every 3rd element)")
print(f"arr[::-1] = {arr_1d[::-1]} (reversed array)")

# Negative indices in slicing
print(f"\nNegative indices in slicing:")
print(f"arr[-4:-1] = {arr_1d[-4:-1]} (last 4 elements, excluding last)")
print(f"arr[-3:] = {arr_1d[-3:]} (last 3 elements)")

# =============================================================================
# 3️⃣ VIEWS vs COPIES - Critical Understanding
# =============================================================================

print("\n3️⃣ Views vs Copies - Memory Behavior")
print("-" * 45)

# Create original array
original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Original array: {original}")

# Slicing creates a VIEW (shares memory)
view_slice = original[2:6]
print(f"View (slice): {view_slice}")

# Modify the view
view_slice[0] = 999
print(f"After modifying view:")
print(f"Original: {original} (CHANGED!)")
print(f"View: {view_slice}")

# Reset for next example
original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Copy creates independent array
copy_array = original[2:6].copy()
print(f"\nOriginal reset: {original}")
print(f"Copy: {copy_array}")

# Modify the copy
copy_array[0] = 888
print(f"After modifying copy:")
print(f"Original: {original} (UNCHANGED)")
print(f"Copy: {copy_array}")

# =============================================================================
# 4️⃣ MULTIDIMENSIONAL INDEXING AND SLICING
# =============================================================================

print("\n4️⃣ Multidimensional Arrays")
print("-" * 45)

# Create 2D array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(f"2D Array (4x4):")
print(arr_2d)

# Single element access
print(f"\nSingle element access:")
print(f"arr[0, 0] = {arr_2d[0, 0]} (top-left)")
print(f"arr[1, 2] = {arr_2d[1, 2]} (row 1, col 2)")
print(f"arr[-1, -1] = {arr_2d[-1, -1]} (bottom-right)")

# Row and column access
print(f"\nRow and column access:")
print(f"arr[1, :] = {arr_2d[1, :]} (entire row 1)")
print(f"arr[:, 2] = {arr_2d[:, 2]} (entire column 2)")
print(f"arr[0] = {arr_2d[0]} (same as arr[0, :])")

# Subarray slicing
print(f"\nSubarray slicing:")
print(f"arr[1:3, 1:3] =")
print(arr_2d[1:3, 1:3])
print(f"arr[:2, -2:] =")
print(arr_2d[:2, -2:])

# =============================================================================
# 5️⃣ BOOLEAN INDEXING - Conditional Selection
# =============================================================================

print("\n5️⃣ Boolean Indexing - Conditional Selection")
print("-" * 50)

# Create array for boolean indexing
data = np.array([1, 15, 3, 8, 12, 7, 20, 5, 18, 10])
print(f"Data array: {data}")

# Create boolean mask
mask_greater_10 = data > 10
print(f"Boolean mask (> 10): {mask_greater_10}")

# Apply boolean indexing
filtered_data = data[mask_greater_10]
print(f"Filtered data (> 10): {filtered_data}")

# Complex conditions
mask_complex = (data > 5) & (data < 15)
print(f"Complex mask (5 < x < 15): {mask_complex}")
print(f"Filtered data (5 < x < 15): {data[mask_complex]}")

# Modify elements using boolean indexing
data_copy = data.copy()
data_copy[data_copy > 15] = 999  # Replace values > 15 with 999
print(f"Modified array (>15 → 999): {data_copy}")

# =============================================================================
# 6️⃣ FANCY INDEXING - Integer Arrays
# =============================================================================

print("\n6️⃣ Fancy Indexing - Integer Arrays")
print("-" * 45)

# Create array for fancy indexing
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(f"Array: {arr}")

# Select specific indices
indices = [1, 3, 5, 7]
fancy_result = arr[indices]
print(f"Indices {indices}: {fancy_result}")

# Fancy indexing with 2D array
arr_2d_fancy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2D Array:")
print(arr_2d_fancy)

# Select specific rows
selected_rows = arr_2d_fancy[[0, 2]]  # Select rows 0 and 2
print(f"Selected rows [0, 2]:")
print(selected_rows)

# Select specific elements
row_indices = [0, 1, 2]
col_indices = [2, 0, 1]
selected_elements = arr_2d_fancy[row_indices, col_indices]
print(f"Selected elements [(0,2), (1,0), (2,1)]: {selected_elements}")

print(f"\n💡 Note: Fancy indexing creates COPIES, not views!")

In [3]:
# =============================================================================
# 🚀 ADVANCED INDEXING TECHNIQUES AND APPLICATIONS
# =============================================================================

print("🚀 Advanced Indexing Techniques")
print("=" * 40)

# =============================================================================
# 7️⃣ COMBINING DIFFERENT INDEXING METHODS
# =============================================================================

print("\n7️⃣ Combining Different Indexing Methods")
print("-" * 45)

# Create 3D array for advanced examples
arr_3d = np.random.randint(1, 100, size=(3, 4, 5))
print(f"3D Array shape: {arr_3d.shape}")
print(f"3D Array:")
print(arr_3d)

# Combine slicing with indexing
print(f"\nCombined indexing examples:")
print(f"arr_3d[0, :, 2] = {arr_3d[0, :, 2]} (slice 0, all rows, col 2)")
print(f"arr_3d[:, 1, :] = \n{arr_3d[:, 1, :]} (all slices, row 1, all cols)")

# Boolean + fancy indexing
data_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\n2D data:")
print(data_2d)

# Find rows where any element > 6
rows_with_large_values = np.any(data_2d > 6, axis=1)
print(f"Rows with values > 6: {rows_with_large_values}")
filtered_rows = data_2d[rows_with_large_values]
print(f"Filtered rows:")
print(filtered_rows)

# =============================================================================
# 8️⃣ CONDITIONAL REPLACEMENT AND MODIFICATION
# =============================================================================

print("\n8️⃣ Conditional Replacement and Modification")
print("-" * 50)

# Create data for modification examples
scores = np.array([85, 92, 78, 96, 88, 73, 91, 82, 95, 79])
print(f"Original scores: {scores}")

# Replace values conditionally
scores_modified = scores.copy()
scores_modified[scores_modified < 80] = 80  # Minimum score of 80
print(f"After minimum 80: {scores_modified}")

# Multiple conditions with np.where
grades = np.where(scores >= 90, 'A', 
                 np.where(scores >= 80, 'B',
                         np.where(scores >= 70, 'C', 'F')))
print(f"Letter grades: {grades}")

# Using np.clip for range limiting
clipped_scores = np.clip(scores, 75, 95)  # Limit to 75-95 range
print(f"Clipped scores (75-95): {clipped_scores}")

# =============================================================================
# 9️⃣ PRACTICAL DATA ANALYSIS EXAMPLES
# =============================================================================

print("\n9️⃣ Practical Data Analysis Examples")
print("-" * 45)

# Simulate a dataset: student scores across subjects
np.random.seed(42)  # For reproducible results
students = ['Alice', 'Bob', 'Carol', 'David', 'Eve']
subjects = ['Math', 'Science', 'English', 'History']
scores_matrix = np.random.randint(70, 100, size=(len(students), len(subjects)))

print(f"Student scores matrix ({len(students)} students, {len(subjects)} subjects):")
print(f"Subjects: {subjects}")
for i, student in enumerate(students):
    print(f"{student:8}: {scores_matrix[i]}")

# Find top performers (average > 85)
averages = np.mean(scores_matrix, axis=1)
print(f"\nStudent averages: {dict(zip(students, averages.round(1)))}")

top_performers = averages > 85
print(f"Top performers (avg > 85): {np.array(students)[top_performers]}")

# Find best subject performance
subject_averages = np.mean(scores_matrix, axis=0)
best_subject_idx = np.argmax(subject_averages)
print(f"Best performing subject: {subjects[best_subject_idx]} (avg: {subject_averages[best_subject_idx]:.1f})")

# Find students who need improvement in specific subjects
math_scores = scores_matrix[:, 0]  # Math is first column
students_need_math_help = math_scores < 80
print(f"Students needing math help: {np.array(students)[students_need_math_help]}")

# =============================================================================
# 🔟 PERFORMANCE COMPARISON: INDEXING METHODS
# =============================================================================

print("\n🔟 Performance Comparison: Indexing Methods")
print("-" * 50)

# Create large array for performance testing
large_array = np.random.rand(1000000)
print(f"Large array size: {large_array.shape}")

# Method 1: Boolean indexing
print("\nTiming boolean indexing:")
%timeit result1 = large_array[large_array > 0.5]

# Method 2: np.where for indices
print("Timing np.where:")
%timeit indices = np.where(large_array > 0.5)[0]; result2 = large_array[indices]

# Method 3: Using loops (BAD practice - for comparison)
def slow_filter(arr, threshold):
    result = []
    for x in arr:
        if x > threshold:
            result.append(x)
    return np.array(result)

print("Timing Python loop (for comparison):")
%timeit result3 = slow_filter(large_array[:1000], 0.5)  # Only 1000 elements for speed

# =============================================================================
# 💡 MEMORY EFFICIENCY TIPS
# =============================================================================

print("\n💡 Memory Efficiency Tips")
print("-" * 30)

# Views save memory
original_array = np.arange(1000000)
print(f"Original array memory: {original_array.nbytes / 1024 / 1024:.2f} MB")

# Slice creates view (shares memory)
view_array = original_array[::2]  # Every other element
print(f"View memory overhead: ~0 MB (shares with original)")

# Copy creates new memory
copy_array = original_array[::2].copy()
print(f"Copy memory: {copy_array.nbytes / 1024 / 1024:.2f} MB (independent)")

# Check if arrays share memory
print(f"View shares memory: {np.shares_memory(original_array, view_array)}")
print(f"Copy shares memory: {np.shares_memory(original_array, copy_array)}")

# =============================================================================
# 🎓 BEST PRACTICES SUMMARY
# =============================================================================

print("\n🎓 Best Practices Summary")
print("-" * 35)
print("✅ Use slicing for subarrays when possible (creates views)")
print("✅ Boolean indexing is very efficient for filtering")
print("✅ Combine conditions with & and | (not 'and'/'or')")
print("✅ Use np.where() for conditional operations")
print("✅ Fancy indexing creates copies - use carefully")
print("✅ Check memory sharing with np.shares_memory()")
print("✅ Use .copy() explicitly when you need independence")
print("✅ Vectorized operations are faster than loops")
print("✅ Test performance with %timeit for critical code")
print("✅ Use negative indices for end-relative access")

🚀 Advanced Indexing Techniques

7️⃣ Combining Different Indexing Methods
---------------------------------------------
3D Array shape: (3, 4, 5)
3D Array:
[[[58 94 66 40 81]
  [92 89  6 32 55]
  [89 60 15 83 73]
  [44 16 94 88 26]]

 [[41 99 64 99  1]
  [38 58 42 36 82]
  [22 78 42 24 87]
  [11 24 97 98 70]]

 [[49 55  3 88  4]
  [78 33 20 45 25]
  [33 16 54 37 67]
  [32 31 16  8 36]]]

Combined indexing examples:
arr_3d[0, :, 2] = [66  6 15 94] (slice 0, all rows, col 2)
arr_3d[:, 1, :] = 
[[92 89  6 32 55]
 [38 58 42 36 82]
 [78 33 20 45 25]] (all slices, row 1, all cols)

2D data:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Rows with values > 6: [False  True  True]
Filtered rows:
[[ 5  6  7  8]
 [ 9 10 11 12]]

8️⃣ Conditional Replacement and Modification
--------------------------------------------------
Original scores: [85 92 78 96 88 73 91 82 95 79]
After minimum 80: [85 92 80 96 88 80 91 82 95 80]
Letter grades: ['B' 'A' 'C' 'A' 'B' 'C' 'A' 'B' 'A' 'C']
Clipped scores (75-95)

In [4]:
# =============================================================================
# 🎮 INTERACTIVE EXAMPLES AND EXERCISES
# =============================================================================

print("🎮 Interactive Examples and Exercises")
print("=" * 45)

# =============================================================================
# 📚 UNDERSTANDING YOUR ORIGINAL EXAMPLE
# =============================================================================

print("\n📚 Understanding Your Original Example")
print("-" * 40)

# Your original code with detailed explanation
import numpy as np

arr = np.arange(10)
print(f"Original array: {arr}")

arr_sliced = arr[5:8]
print(f"Sliced array arr[5:8]: {arr_sliced}")
print(f"Memory shared: {np.shares_memory(arr, arr_sliced)}")

# This modifies the VIEW, which affects the original
arr_sliced[:] = 12
print(f"After arr_sliced[:] = 12:")
print(f"Original array: {arr}")  # CHANGED!
print(f"Sliced array: {arr_sliced}")

print(f"\n💡 Explanation: Slicing creates a VIEW that shares memory!")
print(f"   When you modify arr_sliced, you modify the original arr too.")

# =============================================================================
# 🔄 COMPARING VIEWS vs COPIES
# =============================================================================

print("\n🔄 Comparing Views vs Copies")
print("-" * 35)

# Reset and demonstrate the difference
arr_original = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Fresh array: {arr_original}")

# Method 1: Slice (creates VIEW)
arr_view = arr_original[2:5]
print(f"View: {arr_view}")

# Method 2: Copy (creates independent array)
arr_copy = arr_original[2:5].copy()
print(f"Copy: {arr_copy}")

# Modify both
arr_view[0] = 999
arr_copy[0] = 888

print(f"\nAfter modifications:")
print(f"Original: {arr_original}")  # Only affected by view modification
print(f"View: {arr_view}")
print(f"Copy: {arr_copy}")

# =============================================================================
# 🎯 PRACTICAL EXERCISES
# =============================================================================

print("\n🎯 Practical Exercises")
print("-" * 25)

# Exercise data
data_matrix = np.array([
    [10, 25, 30, 15],
    [20, 35, 40, 25], 
    [30, 45, 50, 35],
    [40, 55, 60, 45],
    [50, 65, 70, 55]
])

print(f"Data matrix (5x4):")
print(data_matrix)

# Exercise 1: Extract specific regions
print(f"\nExercise 1: Extract regions")
top_left = data_matrix[:2, :2]
print(f"Top-left 2x2: \n{top_left}")

bottom_right = data_matrix[-2:, -2:]
print(f"Bottom-right 2x2: \n{bottom_right}")

# Exercise 2: Extract patterns
print(f"\nExercise 2: Extract patterns")
main_diagonal = data_matrix[np.arange(4), np.arange(4)]
print(f"Main diagonal (first 4): {main_diagonal}")

every_other_row = data_matrix[::2, :]
print(f"Every other row: \n{every_other_row}")

# Exercise 3: Conditional operations
print(f"\nExercise 3: Conditional operations")
high_values = data_matrix > 40
print(f"Values > 40 (boolean mask):")
print(high_values)

filtered_values = data_matrix[high_values]
print(f"Actual values > 40: {filtered_values}")

# Exercise 4: Data analysis tasks
print(f"\nExercise 4: Data analysis")
row_sums = np.sum(data_matrix, axis=1)
print(f"Row sums: {row_sums}")

col_means = np.mean(data_matrix, axis=0)
print(f"Column means: {col_means}")

max_in_each_row = np.max(data_matrix, axis=1)
print(f"Max in each row: {max_in_each_row}")

# =============================================================================
# 🔬 ADVANCED INDEXING TRICKS
# =============================================================================

print("\n🔬 Advanced Indexing Tricks")
print("-" * 35)

# Trick 1: Using ellipsis (...) for higher dimensions
arr_3d = np.random.randint(1, 10, (3, 4, 5))
print(f"3D array shape: {arr_3d.shape}")
print(f"Using ellipsis arr_3d[..., 0] shape: {arr_3d[..., 0].shape}")
print(f"Equivalent to arr_3d[:, :, 0]")

# Trick 2: Indexing with conditions on multiple arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 1, 5, 4])
condition = (x > 2) & (y < 5)
print(f"\nMulti-array condition:")
print(f"x: {x}")
print(f"y: {y}")
print(f"x > 2 & y < 5: {condition}")
print(f"x[condition]: {x[condition]}")
print(f"y[condition]: {y[condition]}")

# Trick 3: Using np.ix_ for outer indexing
rows = [0, 2, 4]
cols = [1, 3]
outer_indexed = data_matrix[np.ix_(rows, cols)]
print(f"\nOuter indexing rows {rows}, cols {cols}:")
print(outer_indexed)

# =============================================================================
# 🎨 VISUALIZATION OF INDEXING
# =============================================================================

print("\n🎨 Visualization of Indexing")
print("-" * 35)

# Create a visual representation
visual_array = np.arange(20).reshape(4, 5)
print(f"Visual array (4x5):")
print(visual_array)

# Show different slice results
print(f"\nDifferent slicing patterns:")
print(f"visual_array[1:3, 1:4] =")
print(visual_array[1:3, 1:4])

print(f"\nvisual_array[::2, ::2] =")
print(visual_array[::2, ::2])

print(f"\nvisual_array[:, -2:] =")
print(visual_array[:, -2:])

# =============================================================================
# 📝 SUMMARY OF KEY PATTERNS
# =============================================================================

print("\n📝 Summary of Key Patterns")
print("-" * 35)
print("🔸 arr[i] - Single element")
print("🔸 arr[start:stop] - Range slice")
print("🔸 arr[start:stop:step] - Range with step")
print("🔸 arr[::-1] - Reverse array")
print("🔸 arr[condition] - Boolean filtering")
print("🔸 arr[[i, j, k]] - Fancy indexing")
print("🔸 arr[i, :] - Entire row (2D)")
print("🔸 arr[:, j] - Entire column (2D)")
print("🔸 arr[rows, cols] - Multiple indices")
print("🔸 arr.copy() - Explicit copy")
print("\n💡 Remember: Slicing creates views, fancy indexing creates copies!")

🎮 Interactive Examples and Exercises

📚 Understanding Your Original Example
----------------------------------------
Original array: [0 1 2 3 4 5 6 7 8 9]
Sliced array arr[5:8]: [5 6 7]
Memory shared: True
After arr_sliced[:] = 12:
Original array: [ 0  1  2  3  4 12 12 12  8  9]
Sliced array: [12 12 12]

💡 Explanation: Slicing creates a VIEW that shares memory!
   When you modify arr_sliced, you modify the original arr too.

🔄 Comparing Views vs Copies
-----------------------------------
Fresh array: [0 1 2 3 4 5 6 7 8 9]
View: [2 3 4]
Copy: [2 3 4]

After modifications:
Original: [  0   1 999   3   4   5   6   7   8   9]
View: [999   3   4]
Copy: [888   3   4]

🎯 Practical Exercises
-------------------------
Data matrix (5x4):
[[10 25 30 15]
 [20 35 40 25]
 [30 45 50 35]
 [40 55 60 45]
 [50 65 70 55]]

Exercise 1: Extract regions
Top-left 2x2: 
[[10 25]
 [20 35]]
Bottom-right 2x2: 
[[60 45]
 [70 55]]

Exercise 2: Extract patterns
Main diagonal (first 4): [10 35 50 45]
Every other row:

In [5]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
print(f"\nExample np.where result: {result}")   


Example np.where result: [1.1 2.2 1.3 1.4 2.5]
