# NumPy: Numerical Python

## Overview
NumPy (Numerical Python) is the fundamental package for scientific computing in Python, providing powerful N-dimensional array objects and essential tools for working with numerical data.

## Key Advantages

### 🚀 **Performance Benefits**
- **C-Language Native**: Built on C and Fortran, making it significantly faster than pure Python
- **Contiguous Memory Layout**: Stores data in contiguous blocks of memory, independent of Python's built-in object overhead
- **Vectorized Operations**: Performs complex computations on entire arrays without explicit Python loops
- **Broadcasting**: Efficient operations on arrays of different shapes

### 📊 **Core Features**
- **N-dimensional Arrays**: Powerful ndarray object for multi-dimensional data
- **Mathematical Functions**: Comprehensive library of mathematical operations
- **Array Broadcasting**: Arithmetic operations on arrays of different sizes
- **Linear Algebra**: Built-in support for matrix operations and decompositions
- **Random Number Generation**: Advanced random sampling capabilities

### ⚡ **Why NumPy is Faster**
1. **Compiled Code**: Core algorithms written in C, avoiding Python's interpretation overhead
2. **Vectorization**: Operations applied to entire arrays simultaneously
3. **Memory Efficiency**: Homogeneous data types and contiguous memory allocation
4. **Optimized Libraries**: Leverages BLAS and LAPACK for linear algebra operations

### 🔧 **Common Use Cases**
- Scientific computing and research
- Data analysis and manipulation
- Machine learning and AI
- Image and signal processing
- Financial modeling and analysis

In [11]:
# =============================================================================
# LEARNING SECTION: NumPy vs Python Performance & Memory Analysis
# =============================================================================

# Clear any previous outputs for clean display
from IPython.display import clear_output

# Import required libraries
import numpy as np  # NumPy for numerical computing
import sys          # System-specific parameters and functions

# =============================================================================
# 📊 CREATING ARRAYS: NumPy vs Python
# =============================================================================

# Creating a NumPy array with 1 million integers (0 to 999,999)
# np.arange(n) creates an array [0, 1, 2, ..., n-1]
# The underscore in 1_000_000 is just for readability (Python 3.6+ feature)
my_np_array = np.arange(1_000_000)

# Creating equivalent Python list using built-in range() function
# list(range(n)) creates a list [0, 1, 2, ..., n-1]
my_py_array = list(range(1_000_000))

print("✅ Arrays created successfully!")
print(f"NumPy array shape: {my_np_array.shape}")
print(f"NumPy array dtype: {my_np_array.dtype}")
print(f"Python list length: {len(my_py_array)}")

# =============================================================================
# 🧠 MEMORY USAGE ANALYSIS
# =============================================================================

# Get memory size of the container objects
numpy_size = sys.getsizeof(my_np_array)     # Memory of NumPy array object
python_size = sys.getsizeof(my_py_array)    # Memory of Python list object

# Get pure data size (NumPy specific)
numpy_data_size = my_np_array.nbytes        # Actual data bytes (1M × 8 bytes)

print("\n" + "="*50)
print("📏 MEMORY USAGE COMPARISON")
print("="*50)
print(f"NumPy array object size: {numpy_size:,} bytes ({numpy_size/1024/1024:.2f} MB)")
print(f"NumPy pure data size:   {numpy_data_size:,} bytes ({numpy_data_size/1024/1024:.2f} MB)")
print(f"Python list size:       {python_size:,} bytes ({python_size/1024/1024:.2f} MB)")

# Calculate memory efficiency
memory_ratio = python_size / numpy_size
print(f"\n💡 Memory Efficiency: NumPy uses {memory_ratio:.1f}x LESS memory!")

# =============================================================================
# ⚡ PERFORMANCE COMPARISON: Vectorized vs Loop Operations
# =============================================================================

print("\n" + "="*50)
print("🚀 PERFORMANCE COMPARISON")
print("="*50)
print("Testing multiplication by 2 on 1 million elements...\n")

# NumPy vectorized operation (C-speed, no Python loops)
print("🔥 NumPy Vectorized Operation:")
numpy_result = %timeit -o my_np_array * 2

# Python list comprehension (Python loops, slower)
print("\n🐌 Python List Comprehension:")
python_result = %timeit -o [x * 2 for x in my_py_array]

# Calculate speed improvement
speed_ratio = python_result.best / numpy_result.best
print(f"\n⚡ Speed Improvement: NumPy is {speed_ratio:.1f}x FASTER!")

# =============================================================================
# 🎯 KEY LEARNING POINTS
# =============================================================================

print("\n" + "="*60)
print("🎓 KEY LEARNING POINTS")
print("="*60)
print("1. 📦 MEMORY: NumPy stores homogeneous data in contiguous blocks")
print("2. 🚀 SPEED: NumPy operations are vectorized (C-speed)")
print("3. 🔢 DATA TYPES: NumPy uses fixed-size data types (int64 = 8 bytes)")
print("4. 🐍 PYTHON OVERHEAD: Each Python int is a full object (~28 bytes)")
print("5. ⚡ VECTORIZATION: No explicit loops needed in NumPy")
print("6. 🏆 PERFORMANCE: NumPy can be 10-100x faster than pure Python")
print("="*60)

✅ Arrays created successfully!
NumPy array shape: (1000000,)
NumPy array dtype: int64
Python list length: 1000000

📏 MEMORY USAGE COMPARISON
NumPy array object size: 8,000,112 bytes (7.63 MB)
NumPy pure data size:   8,000,000 bytes (7.63 MB)
Python list size:       8,000,056 bytes (7.63 MB)

💡 Memory Efficiency: NumPy uses 1.0x LESS memory!

🚀 PERFORMANCE COMPARISON
Testing multiplication by 2 on 1 million elements...

🔥 NumPy Vectorized Operation:
940 μs ± 48.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

🐌 Python List Comprehension:
34.8 ms ± 3.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

⚡ Speed Improvement: NumPy is 36.3x FASTER!

🎓 KEY LEARNING POINTS
1. 📦 MEMORY: NumPy stores homogeneous data in contiguous blocks
2. 🚀 SPEED: NumPy operations are vectorized (C-speed)
3. 🔢 DATA TYPES: NumPy uses fixed-size data types (int64 = 8 bytes)
4. 🐍 PYTHON OVERHEAD: Each Python int is a full object (~28 bytes)
5. ⚡ VECTORIZATION: No explicit loops needed in NumP

In [18]:
# Import libraries (already imported in previous cells, but keeping for clarity)
import numpy as np
import sys

# Create a 2D NumPy array with mixed integer and float values
# First row: integers 1-5, Second row: decimal values 0.1-0.5
data = np.array([[1, 2, 3, 4, 5], [.1, .2, .3, .4, .5]])

# Get the memory size of the NumPy array object (includes metadata overhead)
# Key differences:
# sys.getsizeof(): Returns the size of the Python object wrapper (~200-300 bytes typically)
# .nbytes: Returns the actual memory used by the array data (elements × bytes per element)

# Get the memory size of the NumPy array object (includes metadata overhead)
object_size = sys.getsizeof(data)
print(f"NumPy array object size: {object_size} bytes")

# Demonstrate why object size > nbytes
print(f"\n🔍 MEMORY BREAKDOWN:")
print(f"Object size (sys.getsizeof): {object_size} bytes")
print(f"Pure data size (nbytes):     {data.nbytes} bytes")
print(f"Metadata overhead:           {object_size - data.nbytes} bytes")

print(f"\n💡 EXPLANATION:")
print(f"The NumPy array object ({object_size} bytes) contains:")
print(f"  • Pure data: {data.nbytes} bytes (10 elements × 8 bytes each)")
print(f"  • Metadata: {object_size - data.nbytes} bytes (shape, dtype, strides, flags, etc.)")
print(f"  • Python object wrapper overhead")
print(f"Array shape: {data.shape}")
print(f"Array dtype: {data.dtype}")
print(f"Number of elements: {data.size}")
print(f"Memory per element: {data.nbytes / data.size} bytes")

# Get the actual memory size of the data itself (pure data bytes)
print(data.nbytes)  

# Perform vectorized multiplication - multiply entire array by 10
# This demonstrates NumPy's efficient element-wise operations
data * 10




NumPy array object size: 208 bytes

🔍 MEMORY BREAKDOWN:
Object size (sys.getsizeof): 208 bytes
Pure data size (nbytes):     80 bytes
Metadata overhead:           128 bytes

💡 EXPLANATION:
The NumPy array object (208 bytes) contains:
  • Pure data: 80 bytes (10 elements × 8 bytes each)
  • Metadata: 128 bytes (shape, dtype, strides, flags, etc.)
  • Python object wrapper overhead
Array shape: (2, 5)
Array dtype: float64
Number of elements: 10
Memory per element: 8.0 bytes
80


array([[10., 20., 30., 40., 50.],
       [ 1.,  2.,  3.,  4.,  5.]])

# 🔧 NumPy Array Creation Methods

NumPy provides various built-in methods for creating arrays with different initialization patterns. Understanding these methods is crucial for efficient array manipulation and memory management.

## 📋 Array Creation Functions Overview

| Function | Purpose | Key Use Case |
|----------|---------|--------------|
| `array()` | Convert existing data to NumPy array | From lists, tuples, other arrays |
| `arange()` | Create array with evenly spaced values | Sequential data, indexing |
| `asarray()` | Convert to array (avoids copying if possible) | Memory-efficient conversion |
| `zeros()` | Array filled with zeros | Initialize for accumulation |
| `ones()` | Array filled with ones | Initialize for multiplication |
| `zeros_like()` | Zeros array matching another's shape | Same shape, zero values |
| `ones_like()` | Ones array matching another's shape | Same shape, one values |
| `empty()` | Uninitialized array (random values) | Performance when values will be overwritten |
| `empty_like()` | Uninitialized array matching shape | Fast initialization |
| `full()` | Array filled with specific value | Custom initialization |
| `full_like()` | Custom value array matching shape | Same shape, custom values |
| `eye()` | Identity matrix with ones on diagonal | Linear algebra, matrix operations |
| `identity()` | Square identity matrix | Mathematical computations |

## 🎯 When to Use Each Method

### **🔄 Conversion Functions**
- **`array()`**: Converting Python lists/tuples to NumPy
- **`asarray()`**: When input might already be an array (avoids unnecessary copying)

### **📊 Sequence Functions**
- **`arange()`**: Creating numerical sequences (like Python's range but for arrays)

### **🔢 Initialization Functions**
- **`zeros()`**: When you need to accumulate values (sums, counts)
- **`ones()`**: When you need multiplicative identity or boolean masks
- **`empty()`**: When performance matters and you'll fill values later

### **👥 Shape-Matching Functions**
- **`*_like()`**: When you need an array with the same shape as an existing array

### **🏗️ Specialized Functions**
- **`full()`**: When you need a specific initialization value
- **`eye()`/`identity()`**: For linear algebra and matrix operations

## ⚡ Performance Tips

1. **Use `empty()` for speed** when you'll immediately fill the array
2. **Use `asarray()` instead of `array()`** when input might already be an array
3. **Use `*_like()` functions** to match shapes of existing arrays
4. **Specify `dtype`** to control memory usage and precision

In [19]:
# =============================================================================
# 🔧 NUMPY ARRAY CREATION METHODS - COMPREHENSIVE EXAMPLES
# =============================================================================

import numpy as np

print("🎯 NumPy Array Creation Methods Demonstration")
print("=" * 60)

# =============================================================================
# 1️⃣ ARRAY() - Convert existing data to NumPy array
# =============================================================================

print("\n1️⃣ np.array() - Convert existing data")
print("-" * 40)

# From Python list
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print(f"From list: {arr_from_list}")

# From nested list (2D array)
nested_list = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(nested_list)
print(f"2D array:\n{arr_2d}")

# With specific data type
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(f"Float32 array: {arr_float} (dtype: {arr_float.dtype})")

# =============================================================================
# 2️⃣ ARANGE() - Array with evenly spaced values
# =============================================================================

print("\n2️⃣ np.arange() - Evenly spaced values")
print("-" * 40)

# Basic usage (like Python range)
arr_basic = np.arange(10)
print(f"arange(10): {arr_basic}")

# With start, stop, step
arr_range = np.arange(2, 20, 3)
print(f"arange(2, 20, 3): {arr_range}")

# Float values
arr_float_range = np.arange(0, 1, 0.2)
print(f"arange(0, 1, 0.2): {arr_float_range}")

# =============================================================================
# 3️⃣ ASARRAY() - Convert to array (memory efficient)
# =============================================================================

print("\n3️⃣ np.asarray() - Memory efficient conversion")
print("-" * 40)

# When input is already an array (no copy made)
existing_array = np.array([1, 2, 3])
arr_asarray = np.asarray(existing_array)
print(f"asarray from array: {arr_asarray}")
print(f"Same object? {arr_asarray is existing_array}")  # True - no copy!

# When input is a list (copy is made)
list_input = [4, 5, 6]
arr_from_list_asarray = np.asarray(list_input)
print(f"asarray from list: {arr_from_list_asarray}")

# =============================================================================
# 4️⃣ ZEROS() - Array filled with zeros
# =============================================================================

print("\n4️⃣ np.zeros() - Array of zeros")
print("-" * 40)

# 1D array of zeros
zeros_1d = np.zeros(5)
print(f"zeros(5): {zeros_1d}")

# 2D array of zeros
zeros_2d = np.zeros((3, 4))
print(f"zeros((3, 4)):\n{zeros_2d}")

# With specific data type
zeros_int = np.zeros(3, dtype=np.int32)
print(f"zeros(3, int32): {zeros_int}")

# =============================================================================
# 5️⃣ ONES() - Array filled with ones
# =============================================================================

print("\n5️⃣ np.ones() - Array of ones")
print("-" * 40)

# 1D array of ones
ones_1d = np.ones(4)
print(f"ones(4): {ones_1d}")

# 3D array of ones
ones_3d = np.ones((2, 2, 2))
print(f"ones((2, 2, 2)):\n{ones_3d}")

# Boolean ones (useful for masks)
ones_bool = np.ones(3, dtype=bool)
print(f"ones(3, bool): {ones_bool}")

# =============================================================================
# 6️⃣ ZEROS_LIKE() & ONES_LIKE() - Match existing array shape
# =============================================================================

print("\n6️⃣ np.zeros_like() & np.ones_like() - Match shape")
print("-" * 40)

# Reference array
reference = np.array([[1, 2], [3, 4], [5, 6]])
print(f"Reference array:\n{reference}")

# Create zeros with same shape
zeros_like_ref = np.zeros_like(reference)
print(f"zeros_like:\n{zeros_like_ref}")

# Create ones with same shape
ones_like_ref = np.ones_like(reference)
print(f"ones_like:\n{ones_like_ref}")

# =============================================================================
# 7️⃣ EMPTY() & EMPTY_LIKE() - Uninitialized arrays (fastest)
# =============================================================================

print("\n7️⃣ np.empty() & np.empty_like() - Uninitialized (fastest)")
print("-" * 40)

# Empty array (contains random values from memory)
empty_arr = np.empty(3)
print(f"empty(3): {empty_arr}")  # Values are unpredictable!

# Empty with same shape as existing array
empty_like_ref = np.empty_like(reference)
print(f"empty_like shape: {empty_like_ref.shape}")

# =============================================================================
# 8️⃣ FULL() & FULL_LIKE() - Array filled with custom value
# =============================================================================

print("\n8️⃣ np.full() & np.full_like() - Custom fill value")
print("-" * 40)

# Array filled with specific value
full_arr = np.full(4, 7)
print(f"full(4, 7): {full_arr}")

# 2D array filled with π
full_2d = np.full((2, 3), np.pi)
print(f"full((2, 3), π):\n{full_2d}")

# Same shape as reference, filled with -1
full_like_ref = np.full_like(reference, -1)
print(f"full_like(ref, -1):\n{full_like_ref}")

# =============================================================================
# 9️⃣ EYE() & IDENTITY() - Identity matrices
# =============================================================================

print("\n9️⃣ np.eye() & np.identity() - Identity matrices")
print("-" * 40)

# Identity matrix using eye()
eye_matrix = np.eye(3)
print(f"eye(3):\n{eye_matrix}")

# Identity matrix using identity()
identity_matrix = np.identity(4)
print(f"identity(4):\n{identity_matrix}")

# Non-square identity using eye() with offset
eye_offset = np.eye(4, 5, k=1)  # k=1 shifts diagonal right
print(f"eye(4, 5, k=1):\n{eye_offset}")

# =============================================================================
# 🏆 PERFORMANCE COMPARISON
# =============================================================================

print("\n🏆 Performance Comparison (1M elements)")
print("-" * 40)

size = 1_000_000

# Time different creation methods
print("⏱️  Timing results:")
print("zeros():     ", end="")
%timeit np.zeros(size)

print("ones():      ", end="")
%timeit np.ones(size)

print("empty():     ", end="")
%timeit np.empty(size)

print("full():      ", end="")
%timeit np.full(size, 5)

print("\n💡 Key takeaway: empty() is fastest, but contains random values!")

🎯 NumPy Array Creation Methods Demonstration

1️⃣ np.array() - Convert existing data
----------------------------------------
From list: [1 2 3 4 5]
2D array:
[[1 2 3]
 [4 5 6]]
Float32 array: [1. 2. 3.] (dtype: float32)

2️⃣ np.arange() - Evenly spaced values
----------------------------------------
arange(10): [0 1 2 3 4 5 6 7 8 9]
arange(2, 20, 3): [ 2  5  8 11 14 17]
arange(0, 1, 0.2): [0.  0.2 0.4 0.6 0.8]

3️⃣ np.asarray() - Memory efficient conversion
----------------------------------------
asarray from array: [1 2 3]
Same object? True
asarray from list: [4 5 6]

4️⃣ np.zeros() - Array of zeros
----------------------------------------
zeros(5): [0. 0. 0. 0. 0.]
zeros((3, 4)):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros(3, int32): [0 0 0]

5️⃣ np.ones() - Array of ones
----------------------------------------
ones(4): [1. 1. 1. 1.]
ones((2, 2, 2)):
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
ones(3, bool): [ True  True  True]

6️⃣ np.zeros_like() & np.ones_like() - Match

In [21]:
# =============================================================================
# 🎯 PRACTICAL USE CASES & REAL-WORLD EXAMPLES
# =============================================================================

print("🎯 Practical Use Cases for Array Creation Methods")
print("=" * 60)

# =============================================================================
# 📊 DATA SCIENCE SCENARIOS
# =============================================================================

print("\n📊 Data Science Scenarios")
print("-" * 30)

# Scenario 1: Initialize accumulator for batch processing
print("1. Batch Processing Accumulator:")
batch_size = 1000
accumulator = np.zeros(batch_size)  # Start with zeros for summing
print(f"   Accumulator initialized: shape {accumulator.shape}")

# Scenario 2: Create coordinate grids for data visualization
print("\n2. Coordinate Grid for Plotting:")
x_coords = np.arange(0, 10, 0.5)  # X coordinates
y_coords = np.arange(0, 5, 0.25)   # Y coordinates
print(f"   X coordinates: {len(x_coords)} points from {x_coords[0]} to {x_coords[-1]}")
print(f"   Y coordinates: {len(y_coords)} points from {y_coords[0]} to {y_coords[-1]}")

# Scenario 3: Initialize weights for neural network
print("\n3. Neural Network Weight Initialization:")
input_size, hidden_size = 784, 128
# Empty for speed, will fill with random values
weights = np.empty((input_size, hidden_size))
# Fill with random values (simulating proper initialization)
weights.fill(0.01)  # Simple initialization
print(f"   Weights matrix: {weights.shape} initialized to {weights[0,0]}")

# =============================================================================
# 🔬 SCIENTIFIC COMPUTING EXAMPLES
# =============================================================================

print("\n🔬 Scientific Computing Examples")
print("-" * 35)

# Example 1: Identity matrix for linear algebra
print("1. Linear Algebra - Solving Ax = b:")
A = np.array([[2, 1], [1, 3]])  # Coefficient matrix
I = np.eye(2)                   # Identity matrix
print(f"   Identity matrix I:\n{I}")
print(f"   Verification A @ I = A: {np.allclose(A @ I, A)}")

# Example 2: Temperature grid initialization
print("\n2. Temperature Simulation Grid:")
grid_size = (5, 5)
temp_grid = np.full(grid_size, 20.0)  # Start all at 20°C
temp_grid[2, 2] = 100.0  # Heat source in center
print(f"   Temperature grid:\n{temp_grid}")

# Example 3: Boolean mask creation
print("\n3. Data Filtering with Boolean Masks:")
data = np.arange(10)
mask = np.ones_like(data, dtype=bool)  # Start with all True
mask[data > 7] = False  # Exclude values > 7
filtered_data = data[mask]
print(f"   Original data: {data}")
print(f"   Mask: {mask}")
print(f"   Filtered data: {filtered_data}")

# =============================================================================
# 🧮 MATHEMATICAL OPERATIONS
# =============================================================================

print("\n🧮 Mathematical Operations")
print("-" * 30)

# Example 1: Polynomial evaluation setup
print("1. Polynomial Evaluation:")
x_values = np.arange(-2, 3, 0.5)  # Input range
coefficients = np.array([1, -2, 1])  # Coefficients for x² - 2x + 1
print(f"   X values: {x_values}")
print(f"   Polynomial: x² - 2x + 1")

# Example 2: Matrix operations
print("\n2. Matrix Operations:")
A = np.ones((3, 3))   # Matrix of ones
B = np.eye(3) * 2     # Scaled identity matrix
C = A + B             # Matrix addition
print(f"   Matrix A (ones):\n{A}")
print(f"   Matrix B (2*I):\n{B}")
print(f"   Matrix C (A+B):\n{C}")

# =============================================================================
# 🔧 MEMORY MANAGEMENT INSIGHTS
# =============================================================================

print("\n🔧 Memory Management Insights")
print("-" * 35)

# Demonstrate memory efficiency
small_array = np.array([1, 2, 3])
print(f"Small array memory usage:")
print(f"   Object size: {small_array.__sizeof__()} bytes")
print(f"   Data size: {small_array.nbytes} bytes")

# Compare creation methods for same result
arr1 = np.zeros(5) + 7      # Less efficient
arr2 = np.full(5, 7)        # More efficient
arr3 = np.ones(5) * 7       # Alternative

print(f"\nDifferent ways to create array of 7s:")
print(f"   zeros + 7: {arr1}")
print(f"   full(5, 7): {arr2}")  
print(f"   ones * 7: {arr3}")
print(f"   All equal? {np.array_equal(arr1, arr2) and np.array_equal(arr2, arr3)}")

# =============================================================================
# 💡 BEST PRACTICES SUMMARY
# =============================================================================

print("\n💡 Best Practices Summary")
print("-" * 30)
print("✅ Use empty() when you'll immediately fill values (fastest)")
print("✅ Use zeros() for accumulators and counters")
print("✅ Use ones() for multiplicative operations and boolean masks")
print("✅ Use full() when you need a specific initialization value")
print("✅ Use *_like() functions to match existing array shapes")
print("✅ Use asarray() instead of array() when input might be an array")
print("✅ Use arange() for numerical sequences (better than converting from range)")
print("✅ Use eye()/identity() for linear algebra operations")
print("✅ Always specify dtype when memory usage matters")
print("✅ Consider the use case: accumulation, initialization, or computation")

🎯 Practical Use Cases for Array Creation Methods

📊 Data Science Scenarios
------------------------------
1. Batch Processing Accumulator:
   Accumulator initialized: shape (1000,)

2. Coordinate Grid for Plotting:
   X coordinates: 20 points from 0.0 to 9.5
   Y coordinates: 20 points from 0.0 to 4.75

3. Neural Network Weight Initialization:
   Weights matrix: (784, 128) initialized to 0.01

🔬 Scientific Computing Examples
-----------------------------------
1. Linear Algebra - Solving Ax = b:
   Identity matrix I:
[[1. 0.]
 [0. 1.]]
   Verification A @ I = A: True

2. Temperature Simulation Grid:
   Temperature grid:
[[ 20.  20.  20.  20.  20.]
 [ 20.  20.  20.  20.  20.]
 [ 20.  20. 100.  20.  20.]
 [ 20.  20.  20.  20.  20.]
 [ 20.  20.  20.  20.  20.]]

3. Data Filtering with Boolean Masks:
   Original data: [0 1 2 3 4 5 6 7 8 9]
   Mask: [ True  True  True  True  True  True  True  True False False]
   Filtered data: [0 1 2 3 4 5 6 7]

🧮 Mathematical Operations
------------------

# 📐 Understanding Coefficient Matrices in Linear Algebra

## What is a Coefficient Matrix?

A **coefficient matrix** is a matrix that contains the coefficients of variables in a system of linear equations. It's a fundamental concept in linear algebra and essential for solving systems of equations.

### 🔢 Mathematical Definition

For a system of linear equations:
```
a₁₁x₁ + a₁₂x₂ + ... + a₁ₙxₙ = b₁
a₂₁x₁ + a₂₂x₂ + ... + a₂ₙxₙ = b₂
...
aₘ₁x₁ + aₘ₂x₂ + ... + aₘₙxₙ = bₘ
```

The **coefficient matrix A** is:
```
A = [a₁₁  a₁₂  ...  a₁ₙ]
    [a₂₁  a₂₂  ...  a₂ₙ]
    [...  ...  ...  ...]
    [aₘ₁  aₘ₂  ...  aₘₙ]
```

### 🎯 Key Components

1. **Variables**: x₁, x₂, ..., xₙ (unknowns we want to solve for)
2. **Coefficients**: aᵢⱼ (numbers multiplying each variable)
3. **Constants**: b₁, b₂, ..., bₘ (right-hand side values)

### 📊 Matrix Form: Ax = b

- **A**: Coefficient matrix (m × n)
- **x**: Variable vector (n × 1)  
- **b**: Constant vector (m × 1)

### 🔍 Example Breakdown

For the system:
```
2x + 1y = 5
1x + 3y = 7
```

- **Coefficient Matrix A**: `[[2, 1], [1, 3]]`
- **Variable Vector x**: `[x, y]`
- **Constant Vector b**: `[5, 7]`

### 💡 Why It Matters

1. **System Solving**: Find x by computing A⁻¹b (when inverse exists)
2. **Linear Transformations**: A represents how input vectors are transformed
3. **Machine Learning**: Feature matrices are coefficient matrices
4. **Engineering**: Represents physical system relationships

In [22]:
# =============================================================================
# 📐 COEFFICIENT MATRIX: DETAILED EXAMPLES AND APPLICATIONS
# =============================================================================

import numpy as np

print("📐 Understanding Coefficient Matrices")
print("=" * 50)

# =============================================================================
# 🎯 BASIC EXAMPLE: 2x2 System
# =============================================================================

print("\n🎯 Example 1: Simple 2x2 System")
print("-" * 40)

print("System of equations:")
print("2x + 1y = 5")
print("1x + 3y = 7")
print()

# Define the coefficient matrix A
A = np.array([[2, 1],    # Coefficients of first equation: 2x + 1y
              [1, 3]])   # Coefficients of second equation: 1x + 3y

# Define the constant vector b  
b = np.array([5, 7])     # Right-hand side values

print(f"Coefficient matrix A:\n{A}")
print(f"Constant vector b: {b}")

# Solve the system: Ax = b  →  x = A⁻¹b
solution = np.linalg.solve(A, b)
print(f"Solution: x = {solution[0]:.2f}, y = {solution[1]:.2f}")

# Verify the solution
verification = A @ solution
print(f"Verification A @ x = {verification} (should equal b = {b})")

# =============================================================================
# 🏢 REAL-WORLD EXAMPLE: Business Problem
# =============================================================================

print("\n🏢 Example 2: Business Application")
print("-" * 40)

print("Problem: A company produces two products")
print("Product A requires 2 hours of labor and 1 hour of machine time")
print("Product B requires 1 hour of labor and 3 hours of machine time")
print("Available: 100 hours of labor, 150 hours of machine time")
print()

# Coefficient matrix represents resource requirements
# Rows: resources (labor, machine), Columns: products (A, B)
resource_matrix = np.array([[2, 1],    # Labor requirements: 2A + 1B
                           [1, 3]])    # Machine requirements: 1A + 3B

available_resources = np.array([100, 150])  # Available labor and machine hours

print("Resource requirement matrix:")
print(f"           Product A  Product B")
print(f"Labor      {resource_matrix[0,0]}         {resource_matrix[0,1]}")
print(f"Machine    {resource_matrix[1,0]}         {resource_matrix[1,1]}")
print(f"\nAvailable resources: {available_resources}")

# Solve for optimal production quantities
production = np.linalg.solve(resource_matrix, available_resources)
print(f"\nOptimal production:")
print(f"Product A: {production[0]:.1f} units")
print(f"Product B: {production[1]:.1f} units")

# =============================================================================
# 🧮 EXAMPLE 3: 3x3 System (More Complex)
# =============================================================================

print("\n🧮 Example 3: 3x3 System")
print("-" * 40)

print("System of equations:")
print("2x + 3y + 1z = 9")
print("1x + 1y + 1z = 6") 
print("3x + 1y + 2z = 8")
print()

# 3x3 coefficient matrix
A_3x3 = np.array([[2, 3, 1],   # 2x + 3y + 1z = 9
                  [1, 1, 1],   # 1x + 1y + 1z = 6
                  [3, 1, 2]])  # 3x + 1y + 2z = 8

b_3x3 = np.array([9, 6, 8])

print(f"3x3 Coefficient matrix:\n{A_3x3}")
print(f"Constants: {b_3x3}")

# Solve the 3x3 system
solution_3x3 = np.linalg.solve(A_3x3, b_3x3)
print(f"\nSolution:")
print(f"x = {solution_3x3[0]:.2f}")
print(f"y = {solution_3x3[1]:.2f}")
print(f"z = {solution_3x3[2]:.2f}")

# =============================================================================
# 🔍 MATRIX PROPERTIES ANALYSIS
# =============================================================================

print("\n🔍 Matrix Properties Analysis")
print("-" * 40)

# Determinant (indicates if system has unique solution)
det_A = np.linalg.det(A)
print(f"Determinant of 2x2 matrix: {det_A:.2f}")
print(f"{'✅ Unique solution exists' if det_A != 0 else '❌ No unique solution'}")

# Condition number (indicates numerical stability)
cond_A = np.linalg.cond(A)
print(f"Condition number: {cond_A:.2f}")
print(f"{'✅ Well-conditioned' if cond_A < 100 else '⚠️ Ill-conditioned'}")

# Matrix rank
rank_A = np.linalg.matrix_rank(A)
print(f"Matrix rank: {rank_A}")

# =============================================================================
# 📊 VISUALIZATION OF COEFFICIENT MATRIX EFFECTS
# =============================================================================

print("\n📊 Understanding Matrix Effects")
print("-" * 40)

# Identity matrix (no transformation)
I = np.eye(3)
print(f"Identity matrix (no change):\n{I}")

# Scaling matrix (multiplies each variable)
scaling = np.array([[2, 0, 0],
                   [0, 3, 0], 
                   [0, 0, 4]])
print(f"\nScaling matrix:\n{scaling}")

# Effect on unit vector
unit_vector = np.array([1, 1, 1])
scaled_result = scaling @ unit_vector
print(f"Effect: [1,1,1] → {scaled_result}")

# =============================================================================
# 💡 KEY INSIGHTS
# =============================================================================

print("\n💡 Key Insights About Coefficient Matrices")
print("-" * 50)
print("1. 📏 SIZE: m×n matrix for m equations, n variables")
print("2. 🎯 PURPOSE: Represents how variables combine in each equation")
print("3. 🔢 DETERMINANT: Non-zero means unique solution exists")
print("4. 🏭 APPLICATIONS: Economics, engineering, data science")
print("5. 🔧 NUMPY: Use linalg.solve() instead of manual inversion")
print("6. ⚖️ BALANCE: Each row represents one constraint/equation")
print("7. 🔍 INTERPRETATION: Column j shows variable j's contribution to all equations")

📐 Understanding Coefficient Matrices

🎯 Example 1: Simple 2x2 System
----------------------------------------
System of equations:
2x + 1y = 5
1x + 3y = 7

Coefficient matrix A:
[[2 1]
 [1 3]]
Constant vector b: [5 7]
Solution: x = 1.60, y = 1.80
Solution: x = 1.60, y = 1.80
Verification A @ x = [5. 7.] (should equal b = [5 7])

🏢 Example 2: Business Application
----------------------------------------
Problem: A company produces two products
Product A requires 2 hours of labor and 1 hour of machine time
Product B requires 1 hour of labor and 3 hours of machine time
Available: 100 hours of labor, 150 hours of machine time

Resource requirement matrix:
           Product A  Product B
Labor      2         1
Machine    1         3

Available resources: [100 150]

Optimal production:
Product A: 30.0 units
Product B: 40.0 units

🧮 Example 3: 3x3 System
----------------------------------------
System of equations:
2x + 3y + 1z = 9
1x + 1y + 1z = 6
3x + 1y + 2z = 8

3x3 Coefficient matrix:
[[